import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { withAuth, withRateLimit } from '@/lib/auth-middleware-simple'

// Use service role key for database access (bypasses RLS)
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export const POST = withAuth(withRateLimit(10, 60000)(async function(request: NextRequest) {
  try {
    console.log('🚀 TEST ENDPOINT: Starting description generation...')
    console.log('👤 TEST ENDPOINT: Authenticated user:', (request as any).user?.email)
    console.log('👤 TEST ENDPOINT: CMS user role:', (request as any).cmsUser?.role)
    
    const body = await request.json()
    console.log('📦 TEST ENDPOINT: Request body received:', JSON.stringify(body, null, 2))
    
    const { 
      name, 
      city, 
      country, 
      state,
      formatted_address,
      vicinity,
      google_types, 
      rating, 
      user_ratings_total,
      price_level,
      business_status,
      opening_hours,
      website,
      formatted_phone_number,
      photos_references,
      existing_description,
      image_url,
      id: attractionId,
      google_place_id,
      lat: providedLat,
      lng: providedLng,
      reference_links
    } = body

    console.log('✅ TEST ENDPOINT: Required parameters check:', { name: !!name, city: !!city, country: !!country })
    if (!name || !city || !country) {
      console.error('❌ TEST ENDPOINT: Missing required parameters:', { name: !!name, city: !!city, country: !!country })
      return NextResponse.json(
        { error: 'Missing required parameters: name, city, country' },
        { status: 400 }
      )
    }

    const apiKey = process.env.GEMINI_API_KEY
    console.log('🔑 TEST ENDPOINT: API Key check:', apiKey ? 'Configured' : 'NOT CONFIGURED')
    if (!apiKey) {
      console.error('❌ TEST ENDPOINT: Gemini API key not configured')
      return NextResponse.json(
        { error: 'Gemini API key not configured' },
        { status: 500 }
      )
    }

    // Simple prompt for testing
    const prompt = `Write a short description (max 80 words) in Brazilian Portuguese for this tourist attraction:

Name: ${name}
Location: ${city}, ${country}
Types: ${Array.isArray(google_types) ? google_types.join(', ') : google_types || 'tourist_attraction'}
Rating: ${rating ? `${rating}/5` : 'Not available'}

Write only the description in Portuguese, no additional text.`

    console.log('📝 TEST ENDPOINT: Sending prompt to Gemini:', prompt)

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt
              }
            ]
          }
        ],
        generationConfig: {
          temperature: 0.2,
          maxOutputTokens: 200,
        },
      })
    })

    console.log('📡 TEST ENDPOINT: Gemini API response status:', response.status)

    if (!response.ok) {
      const errorData = await response.json()
      console.error('❌ TEST ENDPOINT: Gemini API error:', errorData)
      return NextResponse.json(
        { error: 'Failed to generate description with AI', details: errorData },
        { status: 500 }
      )
    }

    const data = await response.json()
    console.log('📄 TEST ENDPOINT: Gemini API response data:', JSON.stringify(data, null, 2))
    
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text
    
    if (!generatedText) {
      console.error('❌ TEST ENDPOINT: No text generated by Gemini')
      return NextResponse.json(
        { error: 'No description generated by AI' },
        { status: 500 }
      )
    }

    console.log('✅ TEST ENDPOINT: Successfully generated description:', generatedText)

    return NextResponse.json({
      description: generatedText.trim()
    })

  } catch (error) {
    console.error('❌ TEST ENDPOINT: Error generating description:', error)
    console.error('❌ TEST ENDPOINT: Error stack:', error instanceof Error ? error.stack : 'No stack trace')
    return NextResponse.json(
      { error: 'Failed to generate description', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}))
