import { NextRequest, NextResponse } from 'next/server'
import { requireAuth } from '@/lib/core/auth-helpers'
import { DescriptionService } from '@/lib/services/poi-processing/description.service'

/**
 * OPTIMIZED DESCRIPTION GENERATION API
 * 
 * This endpoint now uses DescriptionService for consistency and DRY principle.
 * All description generation logic is centralized in DescriptionService.
 * 
 * Features:
 * - Uses DescriptionService (unified service)
 * - OSM enrichment integration
 * - RAG (scraping) integration
 * - City cache optimization
 * - Quality analysis
 * - Verification system
 * - Audio generation integration
 */
export async function POST(request: NextRequest) {
  try {
    console.log('🚀 Starting OPTIMIZED description generation (using DescriptionService)...')
    
    // Authentication check (DRY - using centralized helper)
    const authResult = await requireAuth(request)
    if (authResult instanceof NextResponse) {
      return authResult // Return error response
    }
    
    const { user_id, user_email } = authResult
    
    const body = await request.json()
    const {
      id: attractionId,
      description_id,
      existing_description,
      use_dynamic_sources = true,
      optimization_mode = true,
      persist_verification = true, // Default to true for API endpoint
      auto_generate_audio = false
    } = body

    // SSOT: If attractionId exists, DescriptionService will fetch ALL data from database
    // Validation is done inside DescriptionService.validatePOIData() (DRY)
    // Only pass ID - service will fetch complete data from core.attractions
    const poiData = {
      id: attractionId // This triggers SSOT - all data fetched from database
    }

    // Prepare options for DescriptionService
    const options = {
      language: 'pt-br',
      use_dynamic_sources: use_dynamic_sources ?? true,
      optimization_mode: optimization_mode ?? true,
      existing_description,
      description_id,
      persist_verification: persist_verification !== false,
      auto_generate_audio: auto_generate_audio || false,
      enrich_with_osm: true,
      skip_enrichment_if_exists: true,
      user_id: user_id!,
      request_id: `api_${Date.now()}`
    }

    console.log('📝 Calling DescriptionService.generate()...')
    
    // Call DescriptionService
    const result = await DescriptionService.generate(poiData, options)

    if (!result.success) {
      console.error('❌ DescriptionService failed:', result.error)
      return NextResponse.json(
        { 
          error: result.error || 'Failed to generate description',
          success: false
        },
        { status: 500 }
      )
    }

    // Extract data from result
    const description = result.data?.description
    const verification = result.data?.verification
    const description_id_result = result.data?.description_id
    const audio_generation = result.data?.audio_generation
    const quality_analysis = result.data?.quality_analysis
    const osm_enrichment = result.data?.osm_enrichment

    if (!description) {
      return NextResponse.json(
        { error: 'No description generated by AI', success: false },
        { status: 500 }
      )
    }

    console.log(`✅ Description generated successfully (${description.length} chars)`)
    console.log(`📊 Verification: ${verification?.aprovada ? 'APPROVED' : 'NEEDS_REVIEW'} (${verification?.pontuacao}/100)`)

    // Prepare response (maintaining compatibility with existing clients)
    return NextResponse.json({
      success: true,
              description: description,
      description_id: description_id_result,
      verification: {
        applied: true,
        approved: verification?.aprovada || false,
        score: verification?.pontuacao || 0,
        detected_dates: verification?.datas_detectadas || [],
        verifiable_facts: verification?.fatos_verificaveis || [],
        issues: verification?.problemas || [],
        improvement_suggestion: verification?.sugestoes_melhoria || '',
        improvement_applied: false // DescriptionService handles improvements internally
      },
      audio_generation: {
        auto_generated: audio_generation?.success || false,
        success: audio_generation?.success || false,
        audio_url: audio_generation?.audio_url,
        error: audio_generation?.error,
        languages: audio_generation?.success ? ['pt-br'] : []
      },
      quality_analysis: quality_analysis ? {
        overall_score: quality_analysis.overall_score,
        confidence_level: quality_analysis.confidence_level,
        justifications: quality_analysis.justifications,
        issues_found: quality_analysis.issues_found,
        recommendations: quality_analysis.recommendations,
        model_used: quality_analysis.model_used,
        data_richness: quality_analysis.data_richness
      } : null,
      osm_enrichment: osm_enrichment ? {
        success: osm_enrichment.success,
        data_quality_score: osm_enrichment.data_quality_score,
        fields_updated: osm_enrichment.fields_updated,
        error: osm_enrichment.error
      } : null,
      metadata: {
        processing_time: result.processing_time,
        model_used: result.metadata?.model_used || 'unknown',
        quality_score: result.metadata?.quality_score || 0,
        status: result.metadata?.status || 'completed',
        timestamp: result.metadata?.timestamp || new Date().toISOString()
      },
      // Legacy fields for backward compatibility
      tokens: [], // Tokens are now handled internally by DescriptionService
      sources_used: 0, // Sources are now handled internally by DescriptionService
      sources_info: [], // Sources are now handled internally by DescriptionService
      optimization_applied: true,
      dynamic_sources_enabled: use_dynamic_sources,
      verification_mode: optimization_mode ? 'maximum' : 'standard',
      model_info: {
        used_model: result.metadata?.model_used || 'gemini-2.5-flash-lite',
        quality_mode: optimization_mode,
        generation_config: optimization_mode ? 'high_quality' : 'standard'
      },
      auto_approval: {
        enabled: auto_generate_audio && verification?.aprovada && verification?.pontuacao >= 75,
        conditions_checked: {
          description_generated: !!description && description.trim().length > 0,
          description_saved: !!description_id_result,
          audio_pt_br_generated: audio_generation?.success || false,
          score_approved: verification?.aprovada && verification?.pontuacao >= 75,
          all_audios_generated: audio_generation?.success || false
        },
        status: auto_generate_audio && attractionId ? 'processed' : 'disabled'
      },
      description_generated: !!description && description.trim().length > 0
    })

  } catch (error: any) {
    console.error('❌ Error in optimized generation:', error)
    return NextResponse.json(
      { 
        error: error.message || 'Internal server error during optimized generation',
        success: false
      },
      { status: 500 }
    )
  }
}
