import { NextRequest, NextResponse } from 'next/server'
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
import { createClient } from '@supabase/supabase-js'
import { cookies } from 'next/headers'

// Service role client for database operations
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

/**
 * OPTIMIZED DESCRIPTION GENERATION API
 * 
 * Features:
 * - English prompts
 * - Verification-optimized generation
 * - Layered sources integration
 * - Token-based indexing
 * - Factuality-focused approach
 */
export async function POST(request: NextRequest) {
  try {
    console.log('🚀 Starting OPTIMIZED description generation...')
    
    // Authentication check
    const supabase = createRouteHandlerClient({ cookies })
    const { data: { session }, error: authError } = await supabase.auth.getSession()
    
    if (authError || !session) {
      console.log('❌ Authentication failed')
      return NextResponse.json(
        { error: 'Unauthorized - Authentication required' },
        { status: 401 }
      )
    }
    
    console.log('✅ User authenticated:', session.user.email)
    
    const body = await request.json()
    const {
      name,
      city,
      country,
      state,
      formatted_address,
      vicinity,
      google_types,
      rating,
      user_ratings_total,
      price_level,
      business_status,
      opening_hours,
      website,
      formatted_phone_number,
      photos_references,
      existing_description,
      image_url,
      id: attractionId,
      google_place_id,
      lat: providedLat,
      lng: providedLng,
      reference_links
    } = body

    console.log('✅ Required parameters check:', { name: !!name, city: !!city, country: !!country })
    
    if (!name || !city || !country) {
      return NextResponse.json(
        { error: 'Missing required parameters: name, city, country' },
        { status: 400 }
      )
    }

    // Get API key
    const apiKey = process.env.GEMINI_API_KEY
    if (!apiKey) {
      return NextResponse.json(
        { error: 'Gemini API key not configured' },
        { status: 500 }
      )
    }

    // Get layered sources for the attraction's location
    const layeredSources = await getLayeredSources(city, country)
    console.log(`📚 Found ${layeredSources.length} layered sources for ${city}, ${country}`)

    // Get existing tokens for RAG optimization
    const existingTokens = await getExistingTokens(attractionId)
    console.log(`🔍 Found ${existingTokens.length} existing tokens for attraction`)

    // Build comprehensive location details
    const locationDetails = buildLocationDetails({ 
      city, 
      country, 
      state, 
      formatted_address, 
      vicinity 
    })

    // Build sources section with layered approach
    const sourcesSection = buildSourcesSection(layeredSources, reference_links)

    // Build Google data section
    const googleData = buildGoogleDataSection({
      google_types,
      rating,
      user_ratings_total,
      price_level,
      business_status,
      google_place_id
    })

    // Create verification-optimized prompt in English
    const prompt = createOptimizedPrompt({
      name,
      locationDetails,
      sourcesSection,
      googleData,
      existingDescription: existing_description,
      existingTokens
    })

    console.log('📝 Sending optimized prompt to Gemini API')
    console.log('🔍 Prompt preview:', prompt.substring(0, 500) + '...')

    // Call Gemini API with optimized configuration
    const response = await callGeminiAPI(prompt, apiKey)

    if (!response.ok) {
      const errorData = await response.json()
      console.error('❌ Gemini API error:', errorData)
      return NextResponse.json(
        { error: 'Failed to generate optimized description', details: errorData },
        { status: 500 }
      )
    }

    const data = await response.json()
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text

    if (!generatedText) {
      return NextResponse.json(
        { error: 'No description generated by AI' },
        { status: 500 }
      )
    }

    // Extract and store tokens for future RAG optimization
    const extractedTokens = await extractAndStoreTokens(
      attractionId, 
      generatedText, 
      { name, city, country, google_types }
    )

    console.log(`✅ Generated optimized description with ${extractedTokens.length} tokens`)

    return NextResponse.json({
      description: generatedText.trim(),
      tokens: extractedTokens,
      sources_used: layeredSources.length,
      optimization_applied: true
    })

  } catch (error) {
    console.error('❌ Error in optimized generation:', error)
    return NextResponse.json(
      { error: 'Internal server error during optimized generation' },
      { status: 500 }
    )
  }
}

/**
 * Get layered sources (national + city) for the location
 */
async function getLayeredSources(city: string, country: string) {
  try {
    // Map country names to codes (based on our analysis)
    const countryCodeMap: Record<string, string> = {
      'Brazil': 'BR',
      'España': 'ES',
      'Spain': 'ES',
      'United States': 'US',
      'USA': 'US',
      'Ireland': 'IE',
      'México': 'MX',
      'Mexico': 'MX',
      'Chile': 'CL'
    }

    const countryCode = countryCodeMap[country] || country

    const { data: sources, error } = await supabaseAdmin
      .schema('core')
      .rpc('get_verification_sources_layered', {
        p_city_name: city,
        p_country_code: countryCode,
        p_limit: 10
      })

    if (error) {
      console.warn('⚠️ Error fetching layered sources:', error)
      return []
    }

    return sources || []
  } catch (error) {
    console.warn('⚠️ Error in getLayeredSources:', error)
    return []
  }
}

/**
 * Get existing tokens for RAG optimization
 */
async function getExistingTokens(attractionId: string) {
  if (!attractionId) return []

  try {
    // Check if we have a tokens table, if not return empty
    const { data: tokens, error } = await supabaseAdmin
      .schema('core')
      .from('attraction_tokens')
      .select('token, weight, context')
      .eq('attraction_id', attractionId)
      .order('weight', { ascending: false })
      .limit(20)

    if (error) {
      console.log('ℹ️ No existing tokens table or tokens found')
      return []
    }

    return tokens || []
  } catch (error) {
    console.log('ℹ️ Tokens system not available yet')
    return []
  }
}

/**
 * Build location details string
 */
function buildLocationDetails({ city, country, state, formatted_address, vicinity }: any) {
  const parts = []
  
  if (city) parts.push(city)
  if (state && state !== city) parts.push(state)
  if (country) parts.push(country)
  
  let locationString = parts.join(', ')
  
  if (formatted_address && formatted_address !== locationString) {
    locationString += ` (${formatted_address})`
  }
  
  if (vicinity && vicinity !== city && vicinity !== formatted_address) {
    locationString += ` - Near: ${vicinity}`
  }
  
  return locationString
}

/**
 * Build sources section with layered approach
 */
function buildSourcesSection(layeredSources: any[], referenceLinks?: string[]) {
  const sections = []

  // National sources (priority 1-3)
  const nationalSources = layeredSources
    .filter(s => s.layer === 'national')
    .slice(0, 3)

  if (nationalSources.length > 0) {
    sections.push('NATIONAL AUTHORITATIVE SOURCES:')
    nationalSources.forEach(source => {
      sections.push(`- ${source.source_name} (${source.source_type}, priority ${source.priority})`)
    })
  }

  // City sources (priority 1-4)
  const citySources = layeredSources
    .filter(s => s.layer === 'city')
    .slice(0, 3)

  if (citySources.length > 0) {
    sections.push('CITY-SPECIFIC SOURCES:')
    citySources.forEach(source => {
      sections.push(`- ${source.source_name} (${source.source_type}, priority ${source.priority})`)
    })
  }

  // Reference links
  if (referenceLinks && referenceLinks.length > 0) {
    const validLinks = referenceLinks.filter(link => link && link.trim())
    if (validLinks.length > 0) {
      sections.push('ADDITIONAL REFERENCES:')
      validLinks.forEach(link => {
        sections.push(`- ${link}`)
      })
    }
  }

  if (sections.length === 0) {
    sections.push('Standard tourism and heritage sources (Wikipedia, official tourism boards)')
  }

  return sections.join('\n')
}

/**
 * Build Google data section
 */
function buildGoogleDataSection({ google_types, rating, user_ratings_total, price_level, business_status, google_place_id }: any) {
  const parts = []
  
  if (google_types && Array.isArray(google_types)) {
    parts.push(`Types: ${google_types.join(', ')}`)
  }
  
  if (rating) {
    const ratingText = user_ratings_total 
      ? `${rating}/5 (${user_ratings_total} reviews)`
      : `${rating}/5`
    parts.push(`Rating: ${ratingText}`)
  }
  
  if (price_level) {
    parts.push(`Price Level: ${'$'.repeat(price_level)}`)
  }
  
  if (business_status && business_status !== 'OPERATIONAL') {
    parts.push(`Status: ${business_status}`)
  }
  
  if (google_place_id) {
    parts.push(`Place ID: ${google_place_id}`)
  }
  
  return parts.length > 0 ? parts.join(' | ') : 'Standard tourist attraction'
}

/**
 * Create optimized prompt in English
 */
function createOptimizedPrompt({ name, locationDetails, sourcesSection, googleData, existingDescription, existingTokens }: any) {
  const hasExistingTokens = existingTokens && existingTokens.length > 0
  const hasExistingDescription = existingDescription && existingDescription.trim()

  return `You are a professional travel guide assistant specializing in factual, verifiable content creation for audio-guided tours.

CRITICAL REQUIREMENTS FOR VERIFICATION ACCEPTANCE:

1. FACTUAL ACCURACY: Use ONLY verifiable facts from authoritative sources listed below
2. VERIFIABLE CLAIMS: Include specific, checkable details (construction years, architects, historical events)  
3. NO SPECULATION: If uncertain about any detail, omit it completely
4. STRUCTURED FACTS: Prioritize facts that can be verified against government databases, heritage sites, or official records
5. AUDIO-OPTIMIZED: Write for text-to-speech with natural rhythm and flow

VERIFICATION CRITERIA (Based on Analysis):
- Target 2-4 verifiable factual claims per description
- Focus on: construction/inauguration years, architects/designers, historical significance, architectural style
- Avoid: subjective descriptions, unverifiable superlatives, speculative information
- Prefer: official sources over secondary sources, government records over general information

${sourcesSection}

TASK: Generate a factual, verification-friendly description in Brazilian Portuguese (max 150 words)

ATTRACTION DATA:
- Name: ${name}
- Location: ${locationDetails}
- Google Data: ${googleData}

${hasExistingTokens ? `
EXISTING KNOWLEDGE TOKENS (for context):
${existingTokens.map((t: any) => `- ${t.token} (weight: ${t.weight}) - ${t.context}`).join('\n')}
` : ''}

${hasExistingDescription ? `
EXISTING DESCRIPTION (for improvement):
${existingDescription}
` : ''}

GENERATION INSTRUCTIONS:

1. START FORMAT: Begin with attraction name and primary verifiable fact
   Example: "O Museu de Arte de São Paulo, inaugurado em 1947..."

2. FACTUAL STRUCTURE:
   - Sentence 1: Name + most important verifiable fact (year, architect, etc.)
   - Sentence 2-3: Additional verifiable details (renovations, historical events, architectural features)
   - Sentence 4: Current function/significance (if verifiable)

3. VERIFICATION OPTIMIZATION:
   - Include specific years only if confirmed by sources
   - Name architects/designers only if documented
   - Mention historical events only if officially recorded
   - Reference architectural styles only if architecturally documented

4. AUDIO OPTIMIZATION:
   - Use short, clear sentences (max 25 words each)
   - Natural breathing points between facts
   - Avoid lists, bullet points, or complex clauses

5. PROHIBITED CONTENT:
   - Neighborhood names, street addresses, directions
   - Opening hours, prices, contact information
   - Subjective superlatives ("most beautiful", "incredible")
   - Unverified claims or speculation

OUTPUT: Only the final Portuguese text, no additional commentary or metadata.`
}

/**
 * Call Gemini API with optimized configuration
 */
async function callGeminiAPI(prompt: string, apiKey: string) {
  const endpoints = [
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${apiKey}`,
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`
  ]

  for (const endpoint of endpoints) {
    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.1,        // Low temperature for factual accuracy
            topK: 20,               // Focused token selection
            topP: 0.8,              // Balanced creativity/accuracy
            maxOutputTokens: 400,   // Sufficient for 150 words + buffer
            stopSequences: ["---", "NOTE:", "ADDITIONAL:"] // Stop at meta content
          },
        })
      })

      if (response.ok) {
        return response
      }

      console.warn(`Failed with endpoint ${endpoint}:`, response.status)
    } catch (error) {
      console.warn(`Error with endpoint ${endpoint}:`, error)
    }
  }

  // Return the last attempt for error handling
  return fetch(endpoints[0], {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: { temperature: 0.1, maxOutputTokens: 400 }
    })
  })
}

/**
 * Extract and store tokens for RAG optimization
 */
async function extractAndStoreTokens(attractionId: string, generatedText: string, metadata: any) {
  if (!attractionId) return []

  try {
    // Extract key tokens from the generated text
    const tokens = extractTokensFromText(generatedText, metadata)

    // Store tokens for future RAG optimization (if table exists)
    try {
      await supabaseAdmin
        .schema('core')
        .from('attraction_tokens')
        .upsert(
          tokens.map(token => ({
            attraction_id: attractionId,
            token: token.token,
            weight: token.weight,
            context: token.context,
            token_type: token.type,
            updated_at: new Date().toISOString()
          })),
          { onConflict: 'attraction_id,token' }
        )
    } catch (error) {
      console.log('ℹ️ Tokens table not available, skipping token storage')
    }

    return tokens
  } catch (error) {
    console.warn('⚠️ Error extracting tokens:', error)
    return []
  }
}

/**
 * Extract tokens from text for RAG optimization
 */
function extractTokensFromText(text: string, metadata: any) {
  const tokens = []

  // Extract years (high weight for verification)
  const years = text.match(/\b(1[0-9]{3}|20[0-9]{2})\b/g) || []
  years.forEach(year => {
    tokens.push({
      token: year,
      weight: 0.9,
      context: `construction_year`,
      type: 'temporal'
    })
  })

  // Extract proper nouns (architects, historical figures)
  const properNouns = text.match(/\b[A-ZÁÉÍÓÚÂÊÔÀÇ][a-záéíóúâêôàç]+(?:\s+[A-ZÁÉÍÓÚÂÊÔÀÇ][a-záéíóúâêôàç]+)*\b/g) || []
  properNouns
    .filter(noun => noun !== metadata.name && noun.length > 3)
    .forEach(noun => {
      tokens.push({
        token: noun,
        weight: 0.7,
        context: 'proper_noun',
        type: 'entity'
      })
    })

  // Extract architectural/style terms
  const architecturalTerms = [
    'neoclássico', 'barroco', 'colonial', 'modernista', 'contemporâneo',
    'gótico', 'art déco', 'brutalista', 'eclético'
  ]
  
  architecturalTerms.forEach(term => {
    if (text.toLowerCase().includes(term)) {
      tokens.push({
        token: term,
        weight: 0.6,
        context: 'architectural_style',
        type: 'style'
      })
    }
  })

  // Extract location-based tokens
  if (metadata.city) {
    tokens.push({
      token: metadata.city,
      weight: 0.8,
      context: 'location_city',
      type: 'location'
    })
  }

  // Extract type-based tokens
  if (metadata.google_types && Array.isArray(metadata.google_types)) {
    metadata.google_types.forEach((type: string) => {
      tokens.push({
        token: type,
        weight: 0.5,
        context: 'attraction_type',
        type: 'category'
      })
    })
  }

  return tokens
}
