/**
 * #487 — the kill switch of `generate-contextual-narration`.
 *
 * Two things are asserted here, and they fail for different reasons:
 *
 * 1. `_shared/feature-flags.ts` fails closed. Every narration generated is a
 *    paid AI call, so an unset, empty or misspelled value must mean OFF. Only
 *    the exact string `true` turns it back on.
 * 2. The refusal leaves the Edge Function as HTTP 200 with `success: false`.
 *    The callers are the native pre-fetch loops already installed on phones —
 *    the app has no OTA, so they cannot be changed. They branch on the
 *    transport error, not on the body: any non-2xx lands on the error branch,
 *    where iOS does not write `failedPreFetchHashes` and re-asks on every
 *    location tick. Turning this back into a 4xx/5xx would cost battery and
 *    data in the field without a single line of the app changing.
 *
 * The helper is Deno source (`Deno.env`, `.ts` specifiers), so it is loaded
 * through a path built at run time — a static import would end in `.ts` and
 * fail `npm run type-check` for the whole repo.
 *
 * Run with: npm run test:api
 */

import { test, before } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

interface FeatureFlagsModule {
  isContextualNarrationEnabled: () => boolean
  CONTEXTUAL_NARRATION_ENABLED_ENV: string
}

const HELPER_PATH = resolve(
  import.meta.dirname,
  '../../supabase/functions/_shared/feature-flags.ts'
)

const FUNCTION_PATH = resolve(
  import.meta.dirname,
  '../../supabase/functions/generate-contextual-narration/index.ts'
)

let flags: FeatureFlagsModule

/** Installs the Deno global the helper reads. Node has no `Deno.env`. */
function setDenoEnv(env: Record<string, string | undefined>): void {
  ;(globalThis as { Deno?: unknown }).Deno = {
    env: { get: (name: string) => env[name] },
  }
}

/** Source of `index.ts` with comments removed, so a comment cannot pass a test. */
function functionCode(): string {
  return readFileSync(FUNCTION_PATH, 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/^\s*\/\/.*$/gm, '')
}

before(async () => {
  setDenoEnv({})
  flags = (await import(pathToFileURL(HELPER_PATH).href)) as FeatureFlagsModule
})

test('#487 — the variable name is declared once, and this is it', () => {
  assert.equal(
    flags.CONTEXTUAL_NARRATION_ENABLED_ENV,
    'CONTEXTUAL_NARRATION_ENABLED'
  )
})

test('#487 — unset means OFF: nothing is generated by default', () => {
  setDenoEnv({})
  assert.equal(flags.isContextualNarrationEnabled(), false)
})

test('#487 — only the exact string `true` turns generation back on', () => {
  setDenoEnv({ CONTEXTUAL_NARRATION_ENABLED: 'true' })
  assert.equal(flags.isContextualNarrationEnabled(), true)

  setDenoEnv({ CONTEXTUAL_NARRATION_ENABLED: ' TRUE ' })
  assert.equal(flags.isContextualNarrationEnabled(), true)
})

test('#487 — anything else fails closed, including the near misses', () => {
  for (const value of ['', ' ', '1', 'yes', 'on', 'false', 'TRUE!', 'enabled']) {
    setDenoEnv({ CONTEXTUAL_NARRATION_ENABLED: value })
    assert.equal(
      flags.isContextualNarrationEnabled(),
      false,
      `value ${JSON.stringify(value)} must not enable generation`
    )
  }
})

test('#487 — the gate is what the function asks, not a hardcoded constant', () => {
  const code = functionCode()
  assert.match(code, /if \(!isContextualNarrationEnabled\(\)\)/)
  assert.doesNotMatch(
    code,
    /const isEnabled\s*=/,
    'the hardcoded flag is gone — the switch is the environment variable'
  )
})

test('#487 — the refusal is HTTP 200 with success:false, for the clients in the field', () => {
  const code = functionCode()
  const gate = code.slice(code.indexOf('if (!isContextualNarrationEnabled())'))
  const refusal = gate.slice(0, gate.indexOf('validateAuthHeader'))

  assert.match(refusal, /success:\s*false/)
  assert.match(refusal, /code:\s*"CONTEXTUAL_NARRATION_DISABLED"/)
  assert.match(refusal, /status:\s*200/)
  assert.doesNotMatch(
    refusal,
    /status:\s*(4|5)\d\d/,
    'a non-2xx lands on the native error branch, which has no negative cache on iOS'
  )
})

test('#487 — the gate runs before auth, rate limit and the AI provider', () => {
  const code = functionCode()
  const gateAt = code.indexOf('if (!isContextualNarrationEnabled())')
  assert.ok(gateAt > 0, 'the gate must exist')

  for (const call of [
    'validateAuthHeader(',
    'checkRateLimit(',
    'generateNarrativeScript(',
    'translateNarrative(',
    'generateAudioWithTTS(',
  ]) {
    const calledAt = code.indexOf(call)
    assert.ok(
      calledAt > gateAt,
      `${call}) must only be reachable after the gate lets the request through`
    )
  }
})
