import { NextRequest, NextResponse } from 'next/server'
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
import { createClient } from '@supabase/supabase-js'
import { cookies } from 'next/headers'

// Service role client for database operations
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

/**
 * DESCRIPTION GENERATION WITH FEEDBACK LOOP
 * 
 * Features:
 * - Analyzes previous verification results
 * - Generates insights for improvement
 * - Applies feedback to create better descriptions
 * - Focuses on verifiable, well-documented information
 */
export async function POST(request: NextRequest) {
  try {
    console.log('🚀 Starting description generation WITH FEEDBACK LOOP...')
    
    // Authentication check
    const supabase = createRouteHandlerClient({ cookies })
    const { data: { session }, error: authError } = await supabase.auth.getSession()
    
    if (authError || !session) {
      console.log('❌ Authentication failed')
      return NextResponse.json(
        { error: 'Unauthorized - Authentication required' },
        { status: 401 }
      )
    }
    
    console.log('✅ User authenticated:', session.user.email)
    
    const body = await request.json()
    const {
      name,
      city,
      country,
      state,
      formatted_address,
      vicinity,
      google_types,
      rating,
      user_ratings_total,
      price_level,
      business_status,
      opening_hours,
      website,
      formatted_phone_number,
      photos_references,
      image_url,
      id: attractionId,
      google_place_id,
      lat: providedLat,
      lng: providedLng,
      reference_links
    } = body

    console.log('✅ Required parameters check:', { name: !!name, city: !!city, country: !!country })
    
    if (!name || !city || !country) {
      return NextResponse.json(
        { error: 'Missing required parameters: name, city, country' },
        { status: 400 }
      )
    }

    // Get API key
    const apiKey = process.env.GEMINI_API_KEY
    if (!apiKey) {
      return NextResponse.json(
        { error: 'Gemini API key not configured' },
        { status: 500 }
      )
    }

    // STEP 1: Analyze previous verification results
    console.log('🔍 STEP 1: Analyzing previous verification results...')
    const feedbackAnalysis = await analyzePreviousVerification(attractionId, name)
    console.log('📊 Feedback analysis:', feedbackAnalysis)

    // STEP 2: Generate improvement insights
    console.log('💡 STEP 2: Generating improvement insights...')
    const improvementInsights = await generateImprovementInsights(feedbackAnalysis, apiKey)
    console.log('🎯 Improvement insights:', improvementInsights)

    // STEP 3: Build enhanced prompt with feedback
    console.log('📝 STEP 3: Building enhanced prompt with feedback...')
    const enhancedPrompt = buildEnhancedPrompt({
      name,
      city,
      country,
      state,
      formatted_address,
      vicinity,
      google_types,
      rating,
      user_ratings_total,
      price_level,
      business_status,
      website,
      reference_links,
      feedbackAnalysis,
      improvementInsights
    })

    // STEP 4: Generate improved description
    console.log('🚀 STEP 4: Generating improved description...')
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: enhancedPrompt }]
        }],
        generationConfig: {
          temperature: 0.3, // Slightly higher for creativity with feedback
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 400, // More space for detailed description
        }
      })
    })

    if (!response.ok) {
      const errorData = await response.json()
      console.error('❌ Gemini API error:', errorData)
      return NextResponse.json(
        { error: 'Failed to generate improved description', details: errorData },
        { status: 500 }
      )
    }

    const data = await response.json()
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text

    if (!generatedText) {
      return NextResponse.json(
        { error: 'No description generated by AI' },
        { status: 500 }
      )
    }

    console.log('✅ Successfully generated improved description with feedback')

    return NextResponse.json({
      description: generatedText.trim(),
      feedback_analysis: feedbackAnalysis,
      improvement_insights: improvementInsights,
      enhanced_generation: true
    })

  } catch (error) {
    console.error('❌ Error in feedback-based generation:', error)
    return NextResponse.json(
      { error: 'Failed to generate description with feedback', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}

/**
 * Analyze previous verification results for the attraction
 */
async function analyzePreviousVerification(attractionId: string, attractionName: string) {
  try {
    // Get the latest verification results
    const { data: latestScore, error: scoreError } = await supabaseAdmin
      .schema('core')
      .from('description_scores')
      .select(`
        score_overall,
        subscores,
        flags,
        reasoning,
        created_at
      `)
      .eq('attraction_id', attractionId)
      .order('created_at', { ascending: false })
      .limit(1)
      .single()

    if (scoreError || !latestScore) {
      console.log('⚠️ No previous verification found, starting fresh')
      return {
        has_previous_verification: false,
        previous_score: null,
        previous_flags: [],
        previous_issues: [],
        improvement_opportunities: ['first_generation']
      }
    }

    // Get claims that were not verified
    const { data: unverifiedClaims, error: claimsError } = await supabaseAdmin
      .schema('core')
      .from('description_claims')
      .select(`
        claim_type,
        slot,
        value,
        verification_status
      `)
      .eq('attraction_id', attractionId)
      .eq('verification_status', 'not_found')

    const analysis = {
      has_previous_verification: true,
      previous_score: latestScore.score_overall,
      previous_subscores: latestScore.subscores,
      previous_flags: latestScore.flags || [],
      previous_issues: extractIssuesFromFlags(latestScore.flags || []),
      unverified_claims: unverifiedClaims || [],
      improvement_opportunities: generateImprovementOpportunities(latestScore, unverifiedClaims || [])
    }

    console.log('📊 Analysis completed:', analysis)
    return analysis

  } catch (error) {
    console.error('❌ Error analyzing previous verification:', error)
    return {
      has_previous_verification: false,
      previous_score: null,
      previous_flags: [],
      previous_issues: [],
      improvement_opportunities: ['analysis_error']
    }
  }
}

/**
 * Generate specific improvement insights using AI
 */
async function generateImprovementInsights(feedbackAnalysis: any, apiKey: string) {
  try {
    const insightsPrompt = `
ANALYSE DE FEEDBACK PARA MELHORIA DE DESCRIÇÃO
===============================================

DADOS DA VERIFICAÇÃO ANTERIOR:
- Score geral: ${feedbackAnalysis.previous_score || 'N/A'}
- Subscores: ${JSON.stringify(feedbackAnalysis.previous_subscores || {})}
- Flags: ${feedbackAnalysis.previous_flags.join(', ') || 'Nenhuma'}
- Claims não verificadas: ${feedbackAnalysis.unverified_claims.length}

OPORTUNIDADES DE MELHORIA IDENTIFICADAS:
${feedbackAnalysis.improvement_opportunities.map((opp: string) => `- ${opp}`).join('\n')}

TAREFA: Analise os dados acima e forneça insights específicos para melhorar a próxima descrição.

FOCOS DE MELHORIA:
1. FACTUALIDADE: Como melhorar a verificação das claims?
2. ESTRUTURA: Como melhorar a organização e clareza?
3. FONTES: Que tipos de informações são mais verificáveis?
4. DETALHES: Que nível de especificidade é ideal?

RESPONDA EM PORTUGUÊS COM INSIGHTS CONCRETOS E ACIONÁVEIS.
`

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: insightsPrompt }]
        }],
        generationConfig: {
          temperature: 0.2,
          maxOutputTokens: 300,
        }
      })
    })

    if (!response.ok) {
      throw new Error('Failed to generate insights')
    }

    const data = await response.json()
    return data.candidates?.[0]?.content?.parts?.[0]?.text || 'Análise não disponível'

  } catch (error) {
    console.error('❌ Error generating insights:', error)
    return 'Análise de melhoria não disponível'
  }
}

/**
 * Build enhanced prompt incorporating feedback
 */
function buildEnhancedPrompt(params: any) {
  const {
    name,
    city,
    country,
    state,
    formatted_address,
    vicinity,
    google_types,
    rating,
    user_ratings_total,
    price_level,
    business_status,
    website,
    reference_links,
    feedbackAnalysis,
    improvementInsights
  } = params

  // Build location context
  const locationContext = [
    `Localização: ${city}, ${country}`,
    state ? `Estado: ${state}` : null,
    formatted_address ? `Endereço: ${formatted_address}` : null,
    vicinity ? `Vizinhança: ${vicinity}` : null
  ].filter(Boolean).join(' | ')

  // Build attraction context
  const attractionContext = [
    `Tipos: ${Array.isArray(google_types) ? google_types.join(', ') : google_types || 'atração turística'}`,
    rating ? `Avaliação: ${rating}/5 (${user_ratings_total || 0} avaliações)` : null,
    price_level ? `Nível de preço: ${price_level}` : null,
    business_status ? `Status: ${business_status}` : null
  ].filter(Boolean).join(' | ')

  // Build feedback context
  const feedbackContext = feedbackAnalysis.has_previous_verification ? `
FEEDBACK DA VERIFICAÇÃO ANTERIOR:
================================
Score anterior: ${feedbackAnalysis.previous_score}%
Problemas identificados: ${feedbackAnalysis.previous_issues.join(', ')}
Claims não verificadas: ${feedbackAnalysis.unverified_claims.length}

INSIGHTS DE MELHORIA:
====================
${improvementInsights}

INSTRUÇÕES ESPECÍFICAS BASEADAS NO FEEDBACK:
- Foque em informações mais facilmente verificáveis
- Evite claims muito específicas ou recentes sem fontes confiáveis
- Priorize informações históricas e bem documentadas
- Use termos mais genéricos quando apropriado
` : ''

  const prompt = `
SISTEMA DE GERAÇÃO DE DESCRIÇÃO COM FEEDBACK INTELIGENTE
=======================================================

ATRAÇÃO: ${name}
${locationContext}
${attractionContext}
${website ? `Website oficial: ${website}` : ''}
${reference_links ? `Links de referência: ${reference_links.join(', ')}` : ''}

${feedbackContext}

CRITÉRIOS DE ACEITAÇÃO PARA VERIFICAÇÃO:
========================================
✅ PRIORIZE informações históricas e bem documentadas
✅ USE datas aproximadas quando exatas não estão disponíveis
✅ FOCE em características arquitetônicas e culturais estabelecidas
✅ INCLUA elementos que podem ser verificados em fontes tradicionais
✅ EVITE informações muito recentes (2023+) sem fontes oficiais
✅ PREFIRA termos genéricos a específicos quando apropriado

FORMATO E ESTRUTURA:
====================
- Máximo 25 segundos de áudio (300-350 caracteres)
- 2-4 frases bem estruturadas
- Início direcional para áudio
- Linguagem clara e acessível
- Foco em experiência do visitante

EXEMPLOS DE INFORMAÇÕES VERIFICÁVEIS:
=====================================
✅ "construído no século XIX" (histórico)
✅ "estilo arquitetônico colonial" (característica estabelecida)
✅ "patrimônio histórico da cidade" (status oficial)
✅ "jardim com espécies nativas" (característica permanente)
✅ "ponto turístico tradicional" (status reconhecido)

❌ EVITE: "inaugurado em dezembro de 2023" (muito recente)
❌ EVITE: "23 metros de comprimento" (detalhe técnico específico)
❌ EVITE: "portal Tori japonês" (elemento muito específico)

GERE UMA DESCRIÇÃO EM PORTUGUÊS BRASILEIRO QUE:
1. Seja otimizada para verificação factual
2. Use informações históricas e bem estabelecidas
3. Mantenha o limite de 25 segundos
4. Seja atrativa para visitantes
5. Aplique os insights de melhoria identificados

DESCRIÇÃO:
`

  return prompt
}

/**
 * Extract issues from verification flags
 */
function extractIssuesFromFlags(flags: string[]): string[] {
  const issues: string[] = []
  
  flags.forEach(flag => {
    switch (flag) {
      case 'low_factuality':
        issues.push('Baixa factualidade')
        break
      case 'no_supported_claims':
        issues.push('Claims não verificadas')
        break
      case 'recent_content':
        issues.push('Conteúdo muito recente')
        break
      case 'specific_measurements':
        issues.push('Medidas muito específicas')
        break
      case 'cultural_content':
        issues.push('Elementos culturais específicos')
        break
      case 'contradiction':
        issues.push('Claims contraditórias')
        break
      default:
        if (flag.startsWith('text_issues:')) {
          issues.push('Problemas de texto')
        }
    }
  })
  
  return issues
}

/**
 * Generate improvement opportunities based on analysis
 */
function generateImprovementOpportunities(score: any, unverifiedClaims: any[]): string[] {
  const opportunities: string[] = []
  
  // Score-based opportunities
  if (score.score_overall < 50) {
    opportunities.push('Melhorar factualidade geral')
  }
  
  if (score.subscores?.factuality < 30) {
    opportunities.push('Focar em informações mais verificáveis')
  }
  
  // Flag-based opportunities
  if (score.flags?.includes('recent_content')) {
    opportunities.push('Usar informações históricas em vez de recentes')
  }
  
  if (score.flags?.includes('specific_measurements')) {
    opportunities.push('Evitar medidas muito específicas')
  }
  
  if (score.flags?.includes('cultural_content')) {
    opportunities.push('Usar termos culturais mais genéricos')
  }
  
  // Claims-based opportunities
  if (unverifiedClaims.length > 0) {
    opportunities.push('Substituir claims não verificadas por alternativas')
  }
  
  // Default opportunities
  if (opportunities.length === 0) {
    opportunities.push('Manter qualidade atual e otimizar estrutura')
  }
  
  return opportunities
}
