import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    console.log('🚀 BASIC ENDPOINT: Starting...')
    
    const body = await request.json()
    console.log('📦 BASIC ENDPOINT: Request body received:', JSON.stringify(body, null, 2))
    
    const { 
      name, 
      city, 
      country, 
      google_types
    } = body

    console.log('✅ BASIC ENDPOINT: Required parameters check:', { name: !!name, city: !!city, country: !!country })
    
    if (!name || !city || !country) {
      console.error('❌ BASIC ENDPOINT: Missing required parameters')
      return NextResponse.json(
        { error: 'Missing required parameters: name, city, country' },
        { status: 400 }
      )
    }

    const apiKey = process.env.GEMINI_API_KEY
    console.log('🔑 BASIC ENDPOINT: API Key check:', apiKey ? 'Configured' : 'NOT CONFIGURED')
    
    if (!apiKey) {
      console.error('❌ BASIC ENDPOINT: Gemini API key not configured')
      return NextResponse.json(
        { error: 'Gemini API key not configured' },
        { status: 500 }
      )
    }

    // Simple prompt for testing
    const prompt = `Write a short description (max 80 words) in Brazilian Portuguese for this tourist attraction:

Name: ${name}
Location: ${city}, ${country}
Types: ${Array.isArray(google_types) ? google_types.join(', ') : google_types || 'tourist_attraction'}

Write only the description in Portuguese, no additional text.`

    console.log('📝 BASIC ENDPOINT: Sending prompt to Gemini:', prompt)

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt
              }
            ]
          }
        ],
        generationConfig: {
          temperature: 0.2,
          maxOutputTokens: 200,
        },
      })
    })

    console.log('📡 BASIC ENDPOINT: Gemini API response status:', response.status)

    if (!response.ok) {
      const errorData = await response.json()
      console.error('❌ BASIC ENDPOINT: Gemini API error:', errorData)
      return NextResponse.json(
        { error: 'Failed to generate description with AI', details: errorData },
        { status: 500 }
      )
    }

    const data = await response.json()
    console.log('📄 BASIC ENDPOINT: Gemini API response data:', JSON.stringify(data, null, 2))
    
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text
    
    if (!generatedText) {
      console.error('❌ BASIC ENDPOINT: No text generated by Gemini')
      return NextResponse.json(
        { error: 'No description generated by AI' },
        { status: 500 }
      )
    }

    console.log('✅ BASIC ENDPOINT: Successfully generated description:', generatedText)

    return NextResponse.json({
      description: generatedText.trim()
    })

  } catch (error) {
    console.error('❌ BASIC ENDPOINT: Error:', error)
    console.error('❌ BASIC ENDPOINT: Error stack:', error instanceof Error ? error.stack : 'No stack trace')
    return NextResponse.json(
      { error: 'Failed to generate description', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
