import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { getSecretKey } from '../_shared/supabase-client.ts';
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
    generateNarrativeScript,
    translateNarrative,
} from "../_shared/contextualGenerator.ts";
import { generateAudioWithTTS } from "../_shared/ttsGenerator.ts";
import { calculateBearing, getDirectionBucket } from "../_shared/utils.ts";
import { validateAuthHeader } from "../_shared/auth-middleware.ts";
import {
    checkRateLimit,
    createRateLimitResponse,
    RATE_LIMIT_CONFIG,
} from "../_shared/rate-limiter.ts";
import { createSecureHeaders } from "../_shared/security-headers.ts";
import {
    createValidationErrorResponse,
    GenerateContextualNarrationSchema,
    validateRequestBody,
} from "../_shared/validation-schemas.ts";
import { createAuditLogger } from "../_shared/audit-logger.ts";
const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers":
        "authorization, x-client-info, apikey, content-type, x-requested-with, accept, origin, referer, user-agent",
};

const PROJECT_URL = Deno.env.get("PROJECT_URL") ||
    Deno.env.get("SUPABASE_URL") || "";
const SERVICE_ROLE_KEY = getSecretKey() ||
    getSecretKey() || "";
const GEMINI_API_KEY = Deno.env.get("GOOGLE_GEMINI_API_KEY") ||
    Deno.env.get("GEMINI_API_KEY") || "";
const GOOGLE_TTS_API_KEY = Deno.env.get("GOOGLE_TTS_API_KEY") ||
    Deno.env.get("GOOGLE_CLOUD_API_KEY") || Deno.env.get("GEMINI_API_KEY") ||
    "";

const supabaseAdmin = createClient(PROJECT_URL, SERVICE_ROLE_KEY);

// ═══════════════════════════════════════════════════════════════════════════════
// REQUEST INTERFACE: All data comes from the frontend, no backend normalization
// ═══════════════════════════════════════════════════════════════════════════════
interface RequestBody {
    action: "generate_text" | "generate_audio" | "wake_up";
    hash: string; // Cache key generated by mobile app (MANDATORY)
    travel_mode: string;
    text_content?: string | null; // For generate_audio: the text to convert to speech

    target_poi: {
        id: string;
        type: string;
        name: string;
        category?: string;
        trigger_radius?: number;
        priority?: number;
        bearing: number;
        distance: number;
        location: { latitude: number; longitude: number };
    };

    user_context: {
        speed: number;
        heading: number;
        language: string;
        accuracy?: number;
        altitude?: number;
        platform?: "ios" | "android";
        app_version?: string;
        timestamp?: number;
        location: { latitude: number; longitude: number };

        previous_poi?: {
            id: string;
            name: string;
            type: string;
            played_at: string;
            location: { latitude: number; longitude: number };
        };

        next_poi?: {
            id: string;
            type: string;
            distance: number;
            bearing: number;
            name: string;
        };

        next_poi_candidates?: {
            id: string;
            name: string;
            type: string;
            category?: string;
            location: { latitude: number; longitude: number };
        }[];

        user_profile?: {
            id: string;
            email?: string;
            name?: string;
            tier: "free" | "premium" | "pro";
        };

        trip_session_id?: string;
        trip_start_timestamp?: number;
    };
}

/**
 * Calculate distance between two coordinates using Haversine formula
 * @returns Distance in meters
 */
function calculateDistance(
    lat1: number,
    lon1: number,
    lat2: number,
    lon2: number,
): number {
    const R = 6371e3; // Earth radius in meters
    const φ1 = lat1 * Math.PI / 180;
    const φ2 = lat2 * Math.PI / 180;
    const Δφ = (lat2 - lat1) * Math.PI / 180;
    const Δλ = (lon2 - lon1) * Math.PI / 180;

    const a = Math.sin(Δφ / 2) * Math.sin(Δφ / 2) +
        Math.cos(φ1) * Math.cos(φ2) *
            Math.sin(Δλ / 2) * Math.sin(Δλ / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

    return R * c; // Distance in meters
}

/**
 * Auto-Heal: Triggers the master generation function in the background
 */
async function triggerMasterGeneration(poiId: string, language: string) {
    try {
        console.log(
            `[Auto-Heal] Starting background master generation for ${poiId}...`,
        );
        const generateDescriptionUrl =
            `${PROJECT_URL}/functions/v1/generate-description`;
        const resp = await fetch(generateDescriptionUrl, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${SERVICE_ROLE_KEY}`,
            },
            body: JSON.stringify({
                poi_id: poiId,
                language: language,
                force: true, // Force fresh master generation
            }),
        });
        console.log(`[Auto-Heal] Status for ${poiId}: ${resp.status}`);
    } catch (err) {
        console.error(
            `[Auto-Heal] Background trigger failed for ${poiId}:`,
            err,
        );
    }
}

serve(async (req: Request): Promise<Response> => {
    if (req.method === "OPTIONS") {
        return new Response("ok", {
            headers: createSecureHeaders(corsHeaders),
        });
    }

    // ✅ FEATURE FLAG (HARDCODED)
    const isEnabled = true; // Ligado: áudio contextual on-demand (play ao se mover)

    if (!isEnabled) {
        return new Response(
            JSON.stringify({
                success: false,
                code: "FEATURE_DISABLED",
                message: "Áudio contextual desabilitado no momento.",
            }),
            {
                status: 200,
                headers: createSecureHeaders(corsHeaders),
            },
        );
    }

    // ✅ VALIDAR AUTENTICAÇÃO
    const authResult = await validateAuthHeader(req);
    if (!authResult.valid) {
        console.warn(
            `[Generate-Contextual-Narration] ❌ Unauthorized: ${authResult.error}`,
        );
        return new Response(
            JSON.stringify({ error: "Unauthorized", detail: authResult.error }),
            { status: 401, headers: createSecureHeaders(corsHeaders) },
        );
    }
    console.log(
        `[Generate-Contextual-Narration] ✅ Authorized: ${authResult.email}`,
    );

    // ✅ RATE LIMITING CHECK
    const config = RATE_LIMIT_CONFIG["generate-contextual-narration"];
    const rateLimit = checkRateLimit(
        req,
        "generate-contextual-narration",
        config.maxRequests,
        config.windowSeconds,
    );
    if (!rateLimit.allowed) {
        console.warn(
            `[Generate-Contextual-Narration] ⚠️ Rate limit exceeded for ${rateLimit.clientId}`,
        );
        return createRateLimitResponse(rateLimit, corsHeaders);
    }
    console.log(
        `[Generate-Contextual-Narration] ✅ Rate limit OK (${rateLimit.remaining} remaining)`,
    );

    try {
        const body = await req.json() as RequestBody;
        const {
            action,
            target_poi,
            travel_mode,
            user_context,
            text_content,
            hash,
        } = body;
        const language = (user_context?.language || "pt-br").toLowerCase();

        // ═══════════════════════════════════════════════════════════════════
        // WAKE UP: Immediate return to warm up the Edge Function
        // ═══════════════════════════════════════════════════════════════════
        if (action === "wake_up") {
            return new Response(JSON.stringify({ status: "awake" }), {
                headers: createSecureHeaders(corsHeaders),
            });
        }

        // ═══════════════════════════════════════════════════════════════════
        // RULE: CHECK PREVIOUS POI (Last POI)
        // If the payload arrives without a last POI (first POI of the trip),
        // we abort generation and assume the App will play a static fallback.
        // ═══════════════════════════════════════════════════════════════════
        if (!user_context?.previous_poi?.id) {
            console.warn(
                `[Rule] First POI (No Previous POI) - Skipping contextual generation.`,
            );
            return new Response(
                JSON.stringify({
                    success: false,
                    code: "NO_PREVIOUS_POI",
                    error: "First POI of trip - defaulting to static audio",
                }),
                {
                    status: 200,
                    headers: createSecureHeaders(corsHeaders),
                },
            );
        }

        // ═══════════════════════════════════════════════════════════════════
        // VALIDATION: Frontend is responsible for sending complete data
        // ═══════════════════════════════════════════════════════════════════
        if (!hash && action !== "wake_up") {
            throw new Error(
                "Missing mandatory 'hash' in request. The mobile app must provide the cache key.",
            );
        }
        if (!target_poi?.id) {
            throw new Error("Missing mandatory 'target_poi.id' in request.");
        }
        if (!user_context?.location) {
            throw new Error(
                "Missing mandatory 'user_context.location' in request.",
            );
        }

        console.log(
            `[Request] Action: ${action} | POI: ${target_poi.name} (${target_poi.id}) | Hash: ${
                hash.substring(0, 8)
            }...`,
        );
        console.log(
            `[Context] Speed: ${user_context.speed}km/h | Heading: ${
                user_context.heading.toFixed(1)
            }° | Platform: ${user_context.platform || "unknown"} v${
                user_context.app_version || "?"
            }`,
        );

        if (user_context.user_profile) {
            console.log(
                `[User] ${user_context.user_profile.name} (${user_context.user_profile.tier})`,
            );
        }

        // ═══════════════════════════════════════════════════════════════════
        // DIRECTION FILTER: Skip if POI is behind (should not happen, but safety check)
        // ═══════════════════════════════════════════════════════════════════
        const directionBucket = getDirectionBucket(
            user_context.heading,
            target_poi.bearing,
        );

        if (directionBucket === "behind") {
            console.warn(
                `[Direction Filter] ⚠️ POI BEHIND detected! ${target_poi.name} (Bearing: ${
                    target_poi.bearing.toFixed(1)
                }°, Heading: ${
                    user_context.heading.toFixed(1)
                }°). This indicates a frontend calculation issue.`,
            );
            return new Response(
                JSON.stringify({
                    success: false,
                    error: "POI is behind user, skipping narration.",
                    code: "POI_BEHIND",
                    data: {
                        bearing: target_poi.bearing,
                        heading: user_context.heading,
                        bucket: "behind",
                    },
                }),
                {
                    status: 200,
                    headers: createSecureHeaders(corsHeaders),
                },
            );
        }

        // ═══════════════════════════════════════════════════════════════════
        // NEXT POI SELECTION: Pick best candidate from frontend list
        // ═══════════════════════════════════════════════════════════════════
        if (
            user_context.next_poi_candidates &&
            user_context.next_poi_candidates.length > 0
        ) {
            let closestCandidate = null;
            let minDistance = Infinity;

            for (const candidate of user_context.next_poi_candidates) {
                if (!candidate.location) continue;

                const dist = calculateDistance(
                    user_context.location.latitude,
                    user_context.location.longitude,
                    candidate.location.latitude,
                    candidate.location.longitude,
                );

                if (dist < minDistance) {
                    minDistance = dist;
                    closestCandidate = candidate;
                }
            }

            if (closestCandidate) {
                const headingToCandidate = calculateBearing(
                    user_context.location.latitude,
                    user_context.location.longitude,
                    closestCandidate.location.latitude,
                    closestCandidate.location.longitude,
                );

                user_context.next_poi = {
                    id: closestCandidate.id,
                    name: closestCandidate.name,
                    type: closestCandidate.type,
                    distance: minDistance,
                    bearing: headingToCandidate,
                };

                console.log(
                    `[Next POI Logic] Selected '${closestCandidate.name}' from ${user_context.next_poi_candidates.length} candidates. Dist: ${
                        Math.round(minDistance)
                    }m`,
                );
            }
        }

        const cacheKey = hash;

        console.log(`[Cache] Using mobile app hash: ${cacheKey}`);

        // 2. CACHE CHECK (Priority 1: Exact Hash + Language)
        const { data: cached } = await supabaseAdmin
            .schema("core")
            .from("cache_narrations")
            .select("*")
            .eq("cache_key", cacheKey)
            .eq("language", language)
            .gt("expires_at", new Date().toISOString())
            .maybeSingle();

        // HIT: Return immediately (Lazy Audio Logic)
        if (cached) {
            if (action === "generate_audio" && !cached.audio_url) {
                // Keep going to MISS audio generation part
            } else {
                console.log(
                    `[Cache Hit: Exact] Returning for ${cacheKey} (${language})`,
                );
                return new Response(
                    JSON.stringify({
                        success: true,
                        data: {
                            text_content: cached.text_content,
                            audio_url: cached.audio_url,
                        },
                    }),
                    { headers: createSecureHeaders(corsHeaders) },
                );
            }
        }

        // MISS (Exact): Pipeline or Translation
        console.log(
            `[Cache Miss: Exact] ${cacheKey} (${language}). Checking for behavioral match in other languages...`,
        );

        let textContent = text_content || cached?.text_content;

        // Priority 2: Otimização de Tradução (Find same behavior in other language)
        if (!textContent) {
            const { data: otherLang } = await supabaseAdmin
                .schema("core")
                .from("cache_narrations")
                .select("text_content, language")
                .eq("cache_key", cacheKey)
                .limit(1)
                .maybeSingle();

            if (otherLang?.text_content) {
                console.log(
                    `[Cache Hit: Translate] Found ${cacheKey} in ${otherLang.language}. Translating to ${language}...`,
                );
                textContent = await translateNarrative(
                    otherLang.text_content,
                    language,
                    GEMINI_API_KEY,
                );

                // Save the translation immediately
                const expiresAt = new Date();
                expiresAt.setDate(expiresAt.getDate() + 30);
                await supabaseAdmin.schema("core").from("cache_narrations")
                    .upsert({
                        cache_key: cacheKey,
                        poi_id: target_poi.id,
                        language: language,
                        travel_mode: travel_mode,
                        direction_bucket: directionBucket,
                        text_content: textContent,
                        expires_at: expiresAt.toISOString(),
                    });
            } else {
                // Priority 3: Full Generation (Optimistic locking for Race Conditions)
                // Try to insert a "Pending" record.
                const expiresAtTemp = new Date();
                expiresAtTemp.setMinutes(expiresAtTemp.getMinutes() + 5); // 5 min temp expiration

                const { error: insertError } = await supabaseAdmin.schema(
                    "core",
                )
                    .from("cache_narrations")
                    .insert({
                        cache_key: cacheKey,
                        poi_id: target_poi.id,
                        language: language,
                        travel_mode: travel_mode,
                        direction_bucket: directionBucket,
                        text_content: null, // PENDING MARKER
                        expires_at: expiresAtTemp.toISOString(),
                    });

                if (insertError) {
                    // 23505 = Unique Violation (Another request beat us to it)
                    if (insertError.code === "23505") {
                        console.log(
                            `[Race Condition] Detected ongoing generation for ${cacheKey}. Waiting...`,
                        );

                        // Polling Loop (Max 15s)
                        for (let i = 0; i < 15; i++) {
                            await new Promise((r) => setTimeout(r, 1000));
                            const { data: retry } = await supabaseAdmin.schema(
                                "core",
                            )
                                .from("cache_narrations")
                                .select("*")
                                .eq("cache_key", cacheKey)
                                .eq("language", language)
                                .maybeSingle();

                            if (retry?.text_content) {
                                console.log(
                                    `[Race Condition] Resolved! returning data for ${cacheKey}`,
                                );
                                return new Response(
                                    JSON.stringify({
                                        success: true,
                                        data: {
                                            text_content: retry.text_content,
                                            audio_url: retry.audio_url,
                                        },
                                    }),
                                    {
                                        headers: createSecureHeaders(
                                            corsHeaders,
                                        ),
                                    },
                                );
                            }
                        }
                        // Fallback if timeout
                        throw new Error(
                            "Timeout waiting for parallel generation",
                        );
                    } else {
                        console.error("[Cache Insert Error]", insertError);
                        // Continue anyway, maybe upsert will fix it later
                    }
                }
            }
        }

        if (!textContent) {
            console.log(
                `[Full Gen] No valid text found for ${target_poi.name} (${target_poi.id}). Calling Gemini...`,
            );

            // ═══════════════════════════════════════════════════════════════════
            // DISTANCE FILTER: Only include previous_poi if within 800m of current target
            // Logic: If POIs are close together, mentioning the previous one adds narrative context
            // ═══════════════════════════════════════════════════════════════════
            let shouldIncludePrevious = false;

            if (user_context.previous_poi?.location && target_poi.location) {
                const distanceBetweenPOIs = calculateDistance(
                    user_context.previous_poi.location.latitude,
                    user_context.previous_poi.location.longitude,
                    target_poi.location.latitude,
                    target_poi.location.longitude,
                );

                shouldIncludePrevious = distanceBetweenPOIs <= 800; // 800m threshold

                if (!shouldIncludePrevious) {
                    console.log(
                        `[Distance Filter] Excluding previous_poi (${user_context.previous_poi.name}) - Distance to target: ${
                            Math.round(distanceBetweenPOIs)
                        }m > 800m`,
                    );
                } else {
                    console.log(
                        `[Distance Filter] Including previous_poi (${user_context.previous_poi.name}) - Distance to target: ${
                            Math.round(distanceBetweenPOIs)
                        }m ≤ 800m`,
                    );
                }
            }

            // Step A: Fetch Rich Context for target and previous POIs
            // Note: next_poi data is received but not used in narration for now (no DB fetch needed)
            const [targetData, prevData] = await Promise.all([
                supabaseAdmin.schema("core").from("attraction_descriptions")
                    .select("*").eq("attraction_id", target_poi.id).eq(
                        "language",
                        language,
                    ).maybeSingle(),
                (user_context.previous_poi && shouldIncludePrevious)
                    ? supabaseAdmin.schema("core").from(
                        "attraction_descriptions",
                    ).select("*").eq(
                        "attraction_id",
                        user_context.previous_poi.id,
                    ).eq("language", language).maybeSingle()
                    : Promise.resolve({ data: null }),
            ]);

            const targetFacts = targetData.data?.facts_pack_json;
            const hasFacts = targetFacts && Array.isArray(targetFacts) &&
                targetFacts.length > 0;
            const hasDescription = targetData.data?.description &&
                targetData.data.description.length > 10;

            if (!targetData.data || !hasDescription) {
                const errorMsg =
                    `[Contextual Narration] Base content missing for target_poi: ${target_poi.id} (${target_poi.name}). Triggering master auto-generation...`;
                console.warn(errorMsg);

                // Full Auto-Heal (Blocker)
                const autoHealTask = triggerMasterGeneration(
                    target_poi.id,
                    language,
                );
                // @ts-ignore
                if (typeof EdgeRuntime !== "undefined") {
                    EdgeRuntime.waitUntil(autoHealTask);
                }

                return new Response(
                    JSON.stringify({
                        success: false,
                        error: "BASE_CONTENT_MISSING",
                        poi_id: target_poi.id,
                    }),
                    { headers: createSecureHeaders(corsHeaders) },
                );
            }

            // Partial Auto-Heal (Non-blocker): We have description but no facts.
            // We proceed with the description but trigger facts generation for next time.
            if (!hasFacts) {
                console.warn(
                    `[Contextual Narration] Facts missing for ${target_poi.id}. Proceeding with description fallback and triggering background healing...`,
                );
                const autoHealTask = triggerMasterGeneration(
                    target_poi.id,
                    language,
                );
                // @ts-ignore
                if (typeof EdgeRuntime !== "undefined") {
                    EdgeRuntime.waitUntil(autoHealTask);
                }
            }

            // Step B: Contextual Script Generation (target + previous only, next_poi reserved for future use)
            textContent = await generateNarrativeScript(
                {
                    ...user_context,
                    travel_mode,
                    language,
                    poi_location: target_poi.location,
                    bearing: target_poi.bearing,
                    // Pass database details for target and previous POIs
                    target_details: {
                        name: targetData.data.attraction_name ||
                            target_poi.name || "POI",
                        description: targetData.data.description,
                        facts: targetData.data.facts_pack_json,
                    },
                    previous_details: prevData.data
                        ? {
                            name: prevData.data.attraction_name ||
                                user_context.previous_poi?.name || "POI",
                            description: prevData.data.description,
                            facts: prevData.data.facts_pack_json,
                        }
                        : undefined,
                    // Note: next_details not passed - reserved for future use
                },
                GEMINI_API_KEY,
            );

            // Save to Cache (TEXT ONLY)
            const expiresAt = new Date();
            expiresAt.setDate(expiresAt.getDate() + 30);

            const { error: upsertErr } = await supabaseAdmin.schema("core")
                .from("cache_narrations").upsert({
                    cache_key: cacheKey,
                    poi_id: target_poi.id,
                    language: language,
                    travel_mode: travel_mode,
                    direction_bucket: directionBucket,
                    text_content: textContent,
                    expires_at: expiresAt.toISOString(),
                });

            if (upsertErr) {
                console.error(
                    "[Cache Save Error] Failed to save text:",
                    upsertErr,
                );
            }
        }

        // ═══════════════════════════════════════════════════════════════════
        // AUDIO GENERATION: Use text_content from payload for generate_audio
        // ═══════════════════════════════════════════════════════════════════
        let audioUrl = cached?.audio_url || null;

        if (action === "generate_audio") {
            // For generate_audio, prefer text_content from payload (sent by frontend)
            const textForTTS = text_content || textContent;

            if (!textForTTS) {
                throw new Error(
                    "Missing text_content for audio generation. Frontend must provide the text.",
                );
            }

            if (!audioUrl) {
                console.log(
                    `[Audio Gen] Generating TTS for ${target_poi.name}...`,
                );
                if (!GOOGLE_TTS_API_KEY) {
                    throw new Error("GOOGLE_TTS_API_KEY is missing");
                }
                const audioBuffer = await generateAudioWithTTS(
                    textForTTS,
                    language,
                    "male",
                    GOOGLE_TTS_API_KEY,
                );

                // Upload
                const fileName = `${target_poi.id}/${cacheKey}_${language}.mp3`;
                const { data: uploadData, error: upErr } = await supabaseAdmin
                    .storage
                    .from("travel-app-audios")
                    .upload(`contextual_audio/${fileName}`, audioBuffer, {
                        contentType: "audio/mpeg",
                        upsert: true,
                    });

                if (upErr) throw upErr;

                const { data: { publicUrl } } = supabaseAdmin.storage
                    .from("travel-app-audios")
                    .getPublicUrl(`contextual_audio/${fileName}`);

                audioUrl = publicUrl;

                // Update Cache with Audio URL
                await supabaseAdmin.schema("core").from("cache_narrations")
                    .update({
                        audio_url: audioUrl,
                    }).eq("cache_key", cacheKey).eq("language", language);
            } else {
                console.log(
                    `[Audio Cache Hit] Returning cached audio for ${target_poi.name}`,
                );
            }
        }

        return new Response(
            JSON.stringify({
                success: true,
                data: {
                    text_content: textContent,
                    audio_url: audioUrl,
                },
            }),
            { headers: createSecureHeaders(corsHeaders) },
        );
    } catch (e) {
        console.error("Narrator Error:", e);
        return new Response(
            JSON.stringify({ success: false, error: String(e) }),
            {
                status: 500,
                headers: createSecureHeaders(corsHeaders),
            },
        );
    }
});
