import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { generateNarrativeScript, translateNarrative } from '../_shared/contextualGenerator.ts';
import { generateAudioWithTTS } from '../_shared/ttsGenerator.ts';
import { getDirectionBucket, calculateBearing } from '../_shared/utils.ts';

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-requested-with, accept, origin, referer, user-agent',
};

const PROJECT_URL = Deno.env.get('PROJECT_URL') || Deno.env.get('SUPABASE_URL') || '';
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || Deno.env.get('SERVICE_ROLE_KEY') || '';
const GEMINI_API_KEY = Deno.env.get('GOOGLE_GEMINI_API_KEY') || Deno.env.get('GEMINI_API_KEY') || '';
const GOOGLE_TTS_API_KEY = Deno.env.get('GOOGLE_TTS_API_KEY') || Deno.env.get('GOOGLE_CLOUD_API_KEY') || Deno.env.get('GEMINI_API_KEY') || '';

const supabaseAdmin = createClient(PROJECT_URL, SERVICE_ROLE_KEY);

interface RequestBody {
    action: 'generate_text' | 'generate_audio';
    hash?: string; // Cache key generated by mobile app
    poi_id?: string; // App root field
    poi_type?: string; // App root field
    bearing?: number; // App root field
    distance?: number; // App root field
    next_poi_id?: string; // App root field
    next_poi_type?: string; // App root field
    target_poi?: {
        id: string;
        name?: string;
        type?: string;
        bearing: number;
        distance: number;
        location: { latitude: number; longitude: number };
    };
    travel_mode: string;
    user_context: {
        location?: { latitude: number; longitude: number };
        speed: number;
        heading: number;
        language: string;
        previous_poi?: {
            id: string;
            name: string;
            type: string;
            played_at: string;
            location: { latitude: number; longitude: number };
        };
        next_poi?: {
            id: string;
            name: string;
            type: string;
            bearing: number;
            location: { latitude: number; longitude: number };
        };
        next_predicted_poi?: {
            id: string;
            name?: string;
            type?: string;
            distance?: number;
            bearing?: number;
            location?: { latitude: number; longitude: number };
        };
    };
}


/**
 * Calculate distance between two coordinates using Haversine formula
 * @returns Distance in meters
 */
function calculateDistance(
    lat1: number, lon1: number,
    lat2: number, lon2: number
): number {
    const R = 6371e3; // Earth radius in meters
    const φ1 = lat1 * Math.PI / 180;
    const φ2 = lat2 * Math.PI / 180;
    const Δφ = (lat2 - lat1) * Math.PI / 180;
    const Δλ = (lon2 - lon1) * Math.PI / 180;

    const a = Math.sin(Δφ / 2) * Math.sin(Δφ / 2) +
        Math.cos(φ1) * Math.cos(φ2) *
        Math.sin(Δλ / 2) * Math.sin(Δλ / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

    return R * c; // Distance in meters
}

async function generateCacheKey(poiId: string, poiType: string, language: string, travelMode: string, directionBucket: string, prevPoiId: string | undefined, nextPoiId: string | undefined, nextPoiType: string | undefined): Promise<string> {
    const data = `${poiId}:${poiType}:${language}:${travelMode}:${directionBucket}:${prevPoiId || 'none'}:${nextPoiId || 'none'}:${nextPoiType || 'none'}`;
    const msgUint8 = new TextEncoder().encode(data);
    const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);
    return Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, '0')).join('');
}


/**
 * Auto-Heal: Triggers the master generation function in the background
 */
async function triggerMasterGeneration(poiId: string, language: string) {
    try {
        console.log(`[Auto-Heal] Starting background master generation for ${poiId}...`);
        const generateDescriptionUrl = `${PROJECT_URL}/functions/v1/generate-description`;
        const resp = await fetch(generateDescriptionUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${SERVICE_ROLE_KEY}`
            },
            body: JSON.stringify({ poi_id: poiId, language: language })
        });
        console.log(`[Auto-Heal] Status for ${poiId}: ${resp.status}`);
    } catch (err) {
        console.error(`[Auto-Heal] Background trigger failed for ${poiId}:`, err);
    }
}

serve(async (req: Request): Promise<Response> => {
    if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

    try {
        const body = await req.json() as RequestBody;
        let { action, target_poi, travel_mode, user_context } = body;
        const language = (user_context?.language || 'pt-br').toLowerCase();

        // NORMALIZE: Handle fields at root level from mobile app
        if (!target_poi && body.poi_id) {
            target_poi = {
                id: body.poi_id,
                type: body.poi_type || 'tuggi',
                bearing: body.bearing || 0,
                distance: body.distance || 0,
                location: user_context?.location || { latitude: 0, longitude: 0 }
            };
        }

        if (!target_poi?.id || !user_context) throw new Error("Missing inputs (target_poi.id or user_context)");

        // NORMALIZE: Handle previous_poi from multiple potential sources
        if (!user_context.previous_poi) {
            // Priority 1: Root object
            // @ts-ignore
            if (body.previous_poi && body.previous_poi.id) {
                // @ts-ignore
                user_context.previous_poi = body.previous_poi;
            }
            // Priority 2: Root IDs
            // @ts-ignore
            else if (body.previous_poi_id || body.last_poi_id) {
                // @ts-ignore
                const prevId = body.previous_poi_id || body.last_poi_id;
                user_context.previous_poi = {
                    id: prevId!,
                    name: "Previous Stop", // Will be enriched from DB later
                    type: "tuggi",
                    played_at: new Date().toISOString(),
                    location: { latitude: 0, longitude: 0 }
                };
            }
        }

        // Normalize next_poi from app's next_predicted_poi or root next_poi_id
        if (body.next_poi_id && !user_context.next_poi) {
            user_context.next_poi = {
                id: body.next_poi_id,
                name: "POI",
                type: body.next_poi_type || "tuggi",
                bearing: 0,
                location: { latitude: 0, longitude: 0 }
            };
        } else if (user_context.next_predicted_poi && !user_context.next_poi) {
            user_context.next_poi = {
                id: user_context.next_predicted_poi.id,
                name: user_context.next_predicted_poi.name || "POI",
                type: user_context.next_predicted_poi.type || "POI",
                bearing: user_context.next_predicted_poi.bearing || 0,
                location: user_context.next_predicted_poi.location || { latitude: 0, longitude: 0 }
            };
        }

        // NORMALIZE: Conditional Fetch - Only query DB if data is missing or invalid
        const needsTargetFix = target_poi.bearing === -1 || !target_poi.location || (user_context.location && target_poi.location.latitude === user_context.location.latitude);
        const needsNextFix = user_context.next_poi && (user_context.next_poi.bearing === -1 || !user_context.next_poi.location || user_context.next_poi.location.latitude === 0);
        const needsPrevFix = user_context.previous_poi && (!user_context.previous_poi.location || user_context.previous_poi.location.latitude === 0);

        if (needsTargetFix || needsNextFix || needsPrevFix) {
            const poiIdsToFetch = [
                needsTargetFix ? target_poi.id : null,
                needsPrevFix ? user_context.previous_poi?.id : null,
                needsNextFix ? user_context.next_poi?.id : null
            ].filter(Boolean) as string[];

            if (poiIdsToFetch.length > 0) {
                console.log(`[Fast Path Skip] Fetching DB coordinates for ${poiIdsToFetch.length} POIs to fix invalid data...`);
                const { data: allCoords } = await supabaseAdmin.schema('core')
                    .from('attraction_coordinate')
                    .select('attraction_id, latitude, longitude')
                    .in('attraction_id', poiIdsToFetch) as { data: { attraction_id: string, latitude: number, longitude: number }[] | null };

                const coordMap = new Map<string, { latitude: number, longitude: number }>(
                    (allCoords || []).map((c: any) => [c.attraction_id, { latitude: c.latitude, longitude: c.longitude }])
                );

                // Update target_poi if needed
                if (needsTargetFix) {
                    const coords = coordMap.get(target_poi.id);
                    if (coords && user_context.location) {
                        target_poi.bearing = calculateBearing(user_context.location.latitude, user_context.location.longitude, coords.latitude, coords.longitude);
                        target_poi.location = { latitude: coords.latitude, longitude: coords.longitude };
                    }
                }

                // Update previous_poi if needed
                if (needsPrevFix && user_context.previous_poi) {
                    const coords = coordMap.get(user_context.previous_poi.id);
                    if (coords) {
                        user_context.previous_poi.location = { latitude: coords.latitude, longitude: coords.longitude };
                    }
                }

                // Update next_poi if needed
                if (needsNextFix && user_context.next_poi && user_context.location) {
                    const coords = coordMap.get(user_context.next_poi.id);
                    if (coords) {
                        user_context.next_poi.bearing = calculateBearing(user_context.location.latitude, user_context.location.longitude, coords.latitude, coords.longitude);
                        user_context.next_poi.location = { latitude: coords.latitude, longitude: coords.longitude };
                    }
                }
            }
        } else {
            console.log(`[Fast Path] Using payload data directly for ${target_poi.id} (Bearing: ${target_poi.bearing.toFixed(1)}°)`);
        }

        // 1. Generate Stable Hash
        const directionBucket = getDirectionBucket(user_context.heading, target_poi.bearing);

        // ✅ DIRECTION FILTER: Skip generation if POI is behind
        if (directionBucket === 'behind') {
            console.warn(`[Direction Filter] Skipping ${target_poi.id} (${target_poi.name || 'POI'}) because it is BEHIND the user (Bearing: ${target_poi.bearing.toFixed(1)}°, Heading: ${user_context.heading.toFixed(1)}°)`);
            return new Response(JSON.stringify({
                success: false,
                error: "POI is behind user, skipping narration.",
                code: "POI_BEHIND",
                data: {
                    bearing: target_poi.bearing,
                    heading: user_context.heading,
                    bucket: "behind"
                }
            }), {
                status: 200,
                headers: { ...corsHeaders, 'Content-Type': 'application/json' }
            });
        }
        // 1. Determine Cache Key (MANDATORY: From Mobile App)
        const cacheKey = body.hash;

        if (!cacheKey) {
            const errorMsg = "Missing mandatory 'hash' in request. The mobile app must provide the cache key.";
            console.error(`[Cache Error] ${errorMsg}`);
            throw new Error(errorMsg);
        }

        console.log(`[Cache] Using mobile app hash: ${cacheKey}`);

        // 2. CACHE CHECK (Priority 1: Exact Hash + Language)
        const { data: cached } = await supabaseAdmin
            .schema('core')
            .from('cache_narrations')
            .select('*')
            .eq('cache_key', cacheKey)
            .eq('language', language)
            .gt('expires_at', new Date().toISOString())
            .maybeSingle();

        // HIT: Return immediately (Lazy Audio Logic)
        if (cached) {
            if (action === 'generate_audio' && !cached.audio_url) {
                // Keep going to MISS audio generation part
            } else {
                console.log(`[Cache Hit: Exact] Returning for ${cacheKey} (${language})`);
                return new Response(JSON.stringify({
                    success: true,
                    data: {
                        text_content: cached.text_content,
                        audio_url: cached.audio_url
                    }
                }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
            }
        }

        // MISS (Exact): Pipeline or Translation
        console.log(`[Cache Miss: Exact] ${cacheKey} (${language}). Checking for behavioral match in other languages...`);

        let textContent = cached?.text_content;

        // Priority 2: Otimização de Tradução (Find same behavior in other language)
        if (!textContent) {
            const { data: otherLang } = await supabaseAdmin
                .schema('core')
                .from('cache_narrations')
                .select('text_content, language')
                .eq('cache_key', cacheKey)
                .limit(1)
                .maybeSingle();

            if (otherLang?.text_content) {
                console.log(`[Cache Hit: Translate] Found ${cacheKey} in ${otherLang.language}. Translating to ${language}...`);
                textContent = await translateNarrative(otherLang.text_content, language, GEMINI_API_KEY);

                // Save the translation immediately
                const expiresAt = new Date();
                expiresAt.setDate(expiresAt.getDate() + 30);
                await supabaseAdmin.schema('core').from('cache_narrations').upsert({
                    cache_key: cacheKey,
                    poi_id: target_poi.id,
                    language: language,
                    travel_mode: travel_mode,
                    direction_bucket: directionBucket,
                    text_content: textContent,
                    expires_at: expiresAt.toISOString()
                });
            }
        }

        if (!textContent) {
            console.log(`[Full Gen] No valid text found for ${target_poi.id}. Calling Gemini...`);

            // ✅ DISTANCE FILTER: Only include previous_poi if within 500m
            let shouldIncludePrevious = false;

            if (user_context.previous_poi?.location && target_poi.location) {
                const distance = calculateDistance(
                    user_context.previous_poi.location.latitude,
                    user_context.previous_poi.location.longitude,
                    target_poi.location.latitude,
                    target_poi.location.longitude
                );

                shouldIncludePrevious = distance <= 400; // 400m threshold (as per verbal instruction)

                if (!shouldIncludePrevious) {
                    console.log(`[Distance Filter] Excluding previous_poi (${user_context.previous_poi.name}) - Distance: ${Math.round(distance)}m > 400m`);
                } else {
                    console.log(`[Distance Filter] Including previous_poi (${user_context.previous_poi.name}) - Distance: ${Math.round(distance)}m ≤ 400m`);
                }
            }

            // Step A: Fetch Rich Context for ALL POIs in the arc
            const [targetData, prevData, nextData] = await Promise.all([
                supabaseAdmin.schema('core').from('attraction_descriptions').select('*').eq('attraction_id', target_poi.id).eq('language', language).maybeSingle(),
                (user_context.previous_poi && shouldIncludePrevious)
                    ? supabaseAdmin.schema('core').from('attraction_descriptions').select('*').eq('attraction_id', user_context.previous_poi.id).eq('language', language).maybeSingle()
                    : Promise.resolve({ data: null }),
                user_context.next_poi
                    ? supabaseAdmin.schema('core').from('attraction_descriptions').select('*').eq('attraction_id', user_context.next_poi.id).eq('language', language).maybeSingle()
                    : Promise.resolve({ data: null })
            ]);

            const targetFacts = targetData.data?.facts_pack_json;
            const hasFacts = targetFacts && Array.isArray(targetFacts) && targetFacts.length > 0;
            const hasDescription = targetData.data?.description && targetData.data.description.length > 10;

            if (!targetData.data || !hasDescription) {
                const errorMsg = `[Contextual Narration] Base content missing for target_poi: ${target_poi.id} (${target_poi.name}). Triggering master auto-generation...`;
                console.warn(errorMsg);

                // Full Auto-Heal (Blocker)
                const autoHealTask = triggerMasterGeneration(target_poi.id, language);
                // @ts-ignore
                if (typeof EdgeRuntime !== 'undefined') { EdgeRuntime.waitUntil(autoHealTask); }

                return new Response(JSON.stringify({
                    success: false,
                    error: "BASE_CONTENT_MISSING",
                    poi_id: target_poi.id
                }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
            }

            // Partial Auto-Heal (Non-blocker): We have description but no facts.
            // We proceed with the description but trigger facts generation for next time.
            if (!hasFacts) {
                console.warn(`[Contextual Narration] Facts missing for ${target_poi.id}. Proceeding with description fallback and triggering background healing...`);
                const autoHealTask = triggerMasterGeneration(target_poi.id, language);
                // @ts-ignore
                if (typeof EdgeRuntime !== 'undefined') { EdgeRuntime.waitUntil(autoHealTask); }
            }

            // Step B: Contextual Script Generation with full arc data
            textContent = await generateNarrativeScript(
                {
                    ...user_context,
                    travel_mode,
                    language,
                    poi_location: target_poi.location,
                    bearing: target_poi.bearing,
                    // Pass full database details for the generator to use
                    target_details: {
                        name: targetData.data.attraction_name || target_poi.name || "POI",
                        description: targetData.data.description,
                        facts: targetData.data.facts_pack_json
                    },
                    previous_details: prevData.data ? {
                        name: prevData.data.attraction_name || user_context.previous_poi?.name || "POI",
                        description: prevData.data.description,
                        facts: prevData.data.facts_pack_json
                    } : undefined,
                    next_details: nextData.data ? {
                        name: nextData.data.attraction_name || user_context.next_poi?.name || "POI",
                        description: nextData.data.description,
                        facts: nextData.data.facts_pack_json
                    } : undefined
                },
                GEMINI_API_KEY
            );

            // Save to Cache (TEXT ONLY)
            const expiresAt = new Date();
            expiresAt.setDate(expiresAt.getDate() + 30);

            const { error: upsertErr } = await supabaseAdmin.schema('core').from('cache_narrations').upsert({
                cache_key: cacheKey,
                poi_id: target_poi.id,
                language: language,
                travel_mode: travel_mode,
                direction_bucket: directionBucket,
                text_content: textContent,
                expires_at: expiresAt.toISOString()
            });

            if (upsertErr) {
                console.error('[Cache Save Error] Failed to save text:', upsertErr);
            }
        }

        // Step C: Audio (Lazy)
        let audioUrl = cached?.audio_url || null;

        if (action === 'generate_audio' && !audioUrl) {
            console.log('[Audio Gen] Generating TTS (Male Voice)...');
            if (!GOOGLE_TTS_API_KEY) throw new Error("GOOGLE_TTS_API_KEY is missing");
            const audioBuffer = await generateAudioWithTTS(textContent, language, 'male', GOOGLE_TTS_API_KEY);

            // Upload
            const fileName = `${target_poi.id}/${cacheKey}_${language}.mp3`;
            const { data: uploadData, error: upErr } = await supabaseAdmin.storage
                .from('travel-app-audios')
                .upload(`contextual_audio/${fileName}`, audioBuffer, { contentType: 'audio/mpeg', upsert: true });

            if (upErr) throw upErr;

            const { data: { publicUrl } } = supabaseAdmin.storage
                .from('travel-app-audios')
                .getPublicUrl(`contextual_audio/${fileName}`);

            audioUrl = publicUrl;

            // Update Cache with Audio URL
            await supabaseAdmin.schema('core').from('cache_narrations').update({
                audio_url: audioUrl
            }).eq('cache_key', cacheKey).eq('language', language);
        }

        return new Response(JSON.stringify({
            success: true,
            data: {
                text_content: textContent,
                audio_url: audioUrl
            }
        }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });

    } catch (e) {
        console.error('Narrator Error:', e);
        return new Response(JSON.stringify({ success: false, error: String(e) }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }
});
