import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

// Cliente sem configuração de schema - especifica schema em cada chamada
const supabase = createClient(supabaseUrl, supabaseKey)

export async function POST(request: NextRequest) {
  try {
    const { pois, sourceFile } = await request.json()
    
    if (!pois || !Array.isArray(pois) || pois.length === 0) {
      return NextResponse.json({ error: 'No POIs provided' }, { status: 400 })
    }

    console.log(`📊 [SUPABASE] Inserting ${pois.length} POIs from ${sourceFile}`)

    // Helper function to extract coordinates from geometry
    const extractCoordinates = (geometry: any): { lat: number, lon: number } => {
      if (geometry?.type === 'Point' && geometry.coordinates) {
        return { lon: geometry.coordinates[0], lat: geometry.coordinates[1] }
      }
      
      // For other geometry types, calculate centroid
      if (geometry?.coordinates) {
        let sumLng = 0, sumLat = 0, count = 0
        
        const processCoords = (coords: any) => {
          if (Array.isArray(coords[0])) {
            coords.forEach(processCoords)
          } else {
            sumLng += coords[0]
            sumLat += coords[1]
            count++
          }
        }
        
        processCoords(geometry.coordinates)
        
        if (count > 0) {
          return { lon: sumLng / count, lat: sumLat / count }
        }
      }
      
      return { lat: 0, lon: 0 }
    }

    // Transform POIs to match database schema
    const transformedPOIs = pois.map(poi => {
      // UUID will be generated automatically by database trigger
      // No need to generate UUID in code - database handles it
      
      // Extract tourism flags from OSM properties
      const extractTourismFlags = (props: any) => ({
        is_historic: props?.historic === 'yes' || props?.historic === 'yes',
        is_touristic: props?.tourism === 'yes' || !!props?.tourism,
        has_train: props?.train === 'yes' || !!props?.train,
        has_ferry: props?.ferry === 'yes' || !!props?.ferry,
        has_bus: props?.bus === 'yes' || !!props?.bus,
        has_wheelchair_access: props?.wheelchair === 'yes' || !!props?.wheelchair,
        has_water: props?.water === 'yes' || !!props?.water,
        has_fishing: props?.fishing === 'yes' || !!props?.fishing,
        has_playground: props?.playground === 'yes' || !!props?.playground,
        is_building: props?.building === 'yes' || !!props?.building,
        has_ruins: props?.ruins === 'yes' || !!props?.ruins
      })
      
      const tourismFlags = extractTourismFlags(poi.osm_properties || poi)
      
      return {
        // uuid_id will be generated by database trigger
        name: poi.name || 'Unnamed POI',
        city: poi.city,
        state: poi.state,
        country: poi.country || 'Brazil',
        neighborhood: poi.neighborhood || null,
        street_name: poi.street_name || null,
        house_number: poi.house_number || null,
        postal_code: poi.postal_code || null,
        formatted_address: poi.formatted_address,
        primary_category: poi.primary_category || poi.category || 'unknown',
        primary_category_type: poi.primary_category_type || null,
        categories: poi.categories || (poi.category ? [poi.category] : null),
        category: poi.category || 'unknown',
        osm_id: poi.osm_id,
        osm_type: poi.osm_type,
        place_id: poi.place_id,
        importance: poi.importance,
        source_file: sourceFile,
        source_type: 'osm',
        osm_properties: poi.osm_properties || poi,
        processing_status: 'completed',
        approved: false, // Default to unapproved
        
        // Contact/Operation fields
        website: poi.website || null,
        contact_phone: poi.contact_phone || null,
        contact_email: poi.contact_email || null,
        operator_name: poi.operator_name || null,
        
        // Accessibility fields
        wheelchair_accessible: poi.wheelchair_accessible || null,
        wheelchair_toilets: poi.wheelchair_toilets || null,
        accessibility_notes: poi.accessibility_notes || null,
        
        // Physical characteristics
        height: poi.height || null,
        building_material: poi.building_material || null,
        building_colour: poi.building_colour || null,
        roof_colour: poi.roof_colour || null,
        architectural_style: poi.architectural_style || null,
        
        // Historical/Heritage fields
        historic_period: poi.historic_period || null,
        landmark_type: poi.landmark_type || null,
        architect: poi.architect || null,
        construction_status: poi.construction_status || null,
        start_date: poi.start_date || null,
        heritage_status: poi.heritage_status || null,
        unesco_status: poi.unesco_status || null,
        unesco_inscription_date: poi.unesco_inscription_date || null,
        unesco_reference: poi.unesco_reference || null,
        landmark_level: poi.landmark_level || null,
        importance_level: poi.importance_level || null,
        
        // Type-specific fields
        museum_type: poi.museum_type || null,
        museum_collection: poi.museum_collection || null,
        museum_audience: poi.museum_audience || null,
        museum_education: poi.museum_education || null,
        leisure_type: poi.leisure_type || null,
        natural_type: poi.natural_type || null,
        natural_water: poi.natural_water || null,
        sport_facilities: poi.sport_facilities || null,
        leisure_playground: poi.leisure_playground || null,
        monument_type: poi.monument_type || null,
        monument_event: poi.monument_event || null,
        monument_person: poi.monument_person || null,
        
        // Infrastructure fields
        parking_capacity: poi.parking_capacity || null,
        public_transport: poi.public_transport || null,
        access_points: poi.access_points || null,
        entrance_fee: poi.entrance_fee || null,
        
        // Environmental fields
        urban_density: poi.urban_density || null,
        noise_level: poi.noise_level || null,
        air_quality: poi.air_quality || null,
        shade_availability: poi.shade_availability || null,
        
        // Cultural fields
        cultural_significance: poi.cultural_significance || null,
        local_traditions: poi.local_traditions || null,
        seasonal_attractions: poi.seasonal_attractions || null,
        
        // Tourism flags
        ...tourismFlags
      }
    })

    // Insert POIs in batches to avoid payload size limits
    const batchSize = 100
    const results = []
    
    for (let i = 0; i < transformedPOIs.length; i += batchSize) {
      const batch = transformedPOIs.slice(i, i + batchSize)
      
      const { data, error } = await supabase
        .schema('homolog')
        .from('pois')
        .upsert(batch, { 
          onConflict: 'uuid_id',
          ignoreDuplicates: false 
        })
        .select('uuid_id')

      if (error) {
        console.error(`❌ [SUPABASE] Error inserting batch ${Math.floor(i / batchSize) + 1}:`, error)
        return NextResponse.json({ 
          success: false, 
          error: `Failed to insert batch: ${error.message}` 
        }, { status: 500 })
      }

      results.push(...(data || []))
      console.log(`✅ [SUPABASE] Batch ${Math.floor(i / batchSize) + 1} inserted: ${batch.length} POIs`)
    }

    console.log(`✅ [SUPABASE] Successfully inserted ${results.length} POIs`)

    // Save coordinates for each POI
    for (let i = 0; i < pois.length; i++) {
      const poi = pois[i]
      const savedPOI = results[i]
      
      if (savedPOI?.uuid_id && poi.lat && poi.lon) {
        try {
          const coordinateData = {
            latitude: poi.lat,
            longitude: poi.lon,
            elevation_m: null,
            boundary_type: 'point',
            boundary_source: 'osm',
            show_in_map: true
          }
          
          const { error: coordError } = await supabase
            .schema('homolog')
            .from('coordinates')
            .insert({
              poi_uuid_id: savedPOI.uuid_id,
              ...coordinateData
            })
          
          if (coordError) {
            console.error(`❌ [SUPABASE] Failed to save coordinates for POI ${poi.name}:`, coordError)
          } else {
            console.log(`✅ [SUPABASE] Coordinates saved for POI: ${poi.name}`)
          }
        } catch (error) {
          console.error(`❌ [SUPABASE] Error saving coordinates for POI ${poi.name}:`, error)
        }
      }
    }

    return NextResponse.json({ 
      success: true, 
      imported: results.length,
      data: results.map(r => ({ uuid_id: r.uuid_id }))
    })

  } catch (error) {
    console.error('❌ [SUPABASE] Error in POIs API:', error)
    return NextResponse.json({ 
      success: false, 
      error: 'Internal server error' 
    }, { status: 500 })
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '50')
    const search = searchParams.get('search') || null
    const city = searchParams.get('city') || null
    const state = searchParams.get('state') || null
    const category = searchParams.get('category') || null
    const onlyComplete = searchParams.get('onlyComplete') === 'true' ? true : null

    const offset = (page - 1) * limit

    console.log(`📊 [SUPABASE] Fetching POIs: page=${page}, limit=${limit}`)

    // Use the custom function for pagination
    const { data, error } = await supabase
      .schema('homolog')
      .rpc('get_pois_paginated', {
        page_limit: limit,
        page_offset: offset,
        search_term: search,
        city_filter: city,
        state_filter: state,
        category_filter: category,
        only_complete: onlyComplete
      })

    if (error) {
      console.error('❌ [SUPABASE] Error fetching POIs:', error)
      return NextResponse.json({ 
        success: false, 
        error: error.message 
      }, { status: 500 })
    }

    const totalCount = data?.[0]?.total_count || 0
    const totalPages = Math.ceil(totalCount / limit)

    console.log(`✅ [SUPABASE] Fetched ${data?.length || 0} POIs (total: ${totalCount})`)

    return NextResponse.json({
      success: true,
      data: data || [],
      pagination: {
        page,
        limit,
        total: totalCount,
        totalPages,
        hasNext: page < totalPages,
        hasPrev: page > 1
      }
    })

  } catch (error) {
    console.error('❌ [SUPABASE] Error in POIs GET API:', error)
    return NextResponse.json({ 
      success: false, 
      error: 'Internal server error' 
    }, { status: 500 })
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const { ids } = await request.json()
    
    if (!ids || !Array.isArray(ids) || ids.length === 0) {
      return NextResponse.json({ error: 'No POI IDs provided' }, { status: 400 })
    }

    console.log(`🗑️ [SUPABASE] Deleting ${ids.length} POIs`)

    const { data, error } = await supabase
      .schema('homolog')
      .from('pois')
      .delete()
      .in('uuid_id', ids)
      .select('uuid_id')

    if (error) {
      console.error('❌ [SUPABASE] Error deleting POIs:', error)
      return NextResponse.json({ 
        success: false, 
        error: error.message 
      }, { status: 500 })
    }

    console.log(`✅ [SUPABASE] Successfully deleted ${data?.length || 0} POIs`)

    return NextResponse.json({
      success: true,
      deleted: data?.length || 0
    })

  } catch (error) {
    console.error('❌ [SUPABASE] Error in POIs DELETE API:', error)
    return NextResponse.json({ 
      success: false, 
      error: 'Internal server error' 
    }, { status: 500 })
  }
}
