import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

// Cliente sem configuração de schema - especifica schema em cada chamada
const supabase = createClient(supabaseUrl, supabaseKey)

export async function POST(request: NextRequest) {
  try {
    const { pois, sourceFile } = await request.json()
    
    if (!pois || !Array.isArray(pois) || pois.length === 0) {
      return NextResponse.json({ error: 'No POIs provided' }, { status: 400 })
    }

    console.log(`📊 [SUPABASE] Inserting ${pois.length} POIs from ${sourceFile}`)

    // Helper function to extract coordinates from geometry
    const extractCoordinates = (geometry: any): { lat: number, lon: number } => {
      if (geometry?.type === 'Point' && geometry.coordinates) {
        return { lon: geometry.coordinates[0], lat: geometry.coordinates[1] }
      }
      
      // For other geometry types, calculate centroid
      if (geometry?.coordinates) {
        let sumLng = 0, sumLat = 0, count = 0
        
        const processCoords = (coords: any) => {
          if (Array.isArray(coords[0])) {
            coords.forEach(processCoords)
          } else {
            sumLng += coords[0]
            sumLat += coords[1]
            count++
          }
        }
        
        processCoords(geometry.coordinates)
        
        if (count > 0) {
          return { lon: sumLng / count, lat: sumLat / count }
        }
      }
      
      return { lat: 0, lon: 0 }
    }

    // Transform POIs to match database schema
    const transformedPOIs = pois.map(poi => {
      // POIs come from processPOI with structure: { _id, properties, geometry }
      // We need to access poi.properties for all data
      const props = poi.properties || poi
      
          // Extract coordinates for UUID generation
          const coords = extractCoordinates(poi.geometry)
      
      // Extract tourism flags from already-processed properties
      const tourismFlags = {
        is_historic: props.is_historic || false,
        is_touristic: props.is_touristic || false,
        has_train: props.has_train || false,
        has_ferry: props.has_ferry || false,
        has_bus: props.has_bus || false,
        has_wheelchair_access: props.has_wheelchair_access || false,
        has_water: props.has_water || false,
        has_fishing: props.has_fishing || false,
        has_playground: props.has_playground || false,
        is_building: props.is_building || false,
        has_ruins: props.has_ruins || false
      }
      
      return {
        // uuid_id will be generated by RPC
        name: props.name || 'Unnamed POI',
        city: props.city,
        state: props.state,
        country: props.country || 'Brazil',
        neighborhood: props.neighborhood || null,
        street_name: props.street_name || null,
        house_number: props.house_number || null,
        postal_code: props.postal_code || null,
        formatted_address: props.formatted_address,
        primary_category: props.primary_category || props.category || 'unknown',
        primary_category_type: props.primary_category_type || null,
        categories: props.categories || (props.category ? [props.category] : null),
        category: props.category || 'unknown',
        osm_id: props.osm_id,
        osm_type: props.osm_type,
        place_id: props.place_id,
        importance: props.importance,
        source_file: sourceFile,
        source_type: 'osm',
        osm_properties: props.osm_properties || props,
        processing_status: 'completed',
        approved: false,
        
        // Additional fields from schema
        description: props.description || null,
        is_complete: !!(props.name && props.city && props.state),
        has_nominatim_data: props.has_nominatim_data || false,
        osm_geometry: poi.geometry ? JSON.stringify(poi.geometry) : null,
        
        // Send coordinates for UUID generation
        lat: coords.lat,
        lon: coords.lon,
        
        // Contact/Operation fields
        website: props.website || null,
        contact_phone: props.contact_phone || null,
        contact_email: props.contact_email || null,
        operator_name: props.operator_name || null,
        
        // Accessibility fields
        wheelchair_accessible: props.wheelchair_accessible || null,
        wheelchair_toilets: props.wheelchair_toilets || null,
        accessibility_notes: props.accessibility_notes || null,
        
            // Physical characteristics - extract height and elevation
            height_m: props.height || null,
            elevation_m: props.elevation || null,
        building_material: props.building_material || null,
        building_colour: props.building_colour || null,
        roof_colour: props.roof_colour || null,
        architectural_style: props.architectural_style || null,
        
        // Historical/Heritage fields
        historic_period: props.historic_period || null,
        landmark_type: props.landmark_type || null,
        architect: props.architect || null,
        construction_status: props.construction_status || null,
        start_date: props.start_date || null,
        heritage_status: props.heritage_status || null,
        unesco_status: props.unesco_status || null,
        unesco_inscription_date: props.unesco_inscription_date || null,
        unesco_reference: props.unesco_reference || null,
        landmark_level: props.landmark_level || null,
        importance_level: props.importance_level || null,
        
        // Type-specific fields
        museum_type: props.museum_type || null,
        museum_collection: props.museum_collection || null,
        museum_audience: props.museum_audience || null,
        museum_education: props.museum_education || null,
        leisure_type: props.leisure_type || null,
        natural_type: props.natural_type || null,
        natural_water: props.natural_water || null,
        sport_facilities: props.sport_facilities || null,
        leisure_playground: props.leisure_playground || null,
        monument_type: props.monument_type || null,
        monument_event: props.monument_event || null,
        monument_person: props.monument_person || null,
        
        // Infrastructure fields
        parking_capacity: props.parking_capacity || null,
        public_transport: props.public_transport || null,
        access_points: props.access_points || null,
        entrance_fee: props.entrance_fee || null,
        
        // Environmental fields
        urban_density: props.urban_density || null,
        noise_level: props.noise_level || null,
        air_quality: props.air_quality || null,
        shade_availability: props.shade_availability || null,
        
        // Cultural fields
        cultural_significance: props.cultural_significance || null,
        local_traditions: props.local_traditions || null,
        seasonal_attractions: props.seasonal_attractions || null,
        
        // Tourism flags
        ...tourismFlags
      }
    })

    // Insert POIs using RPC function for UUID generation
    const results = []
    
    for (let i = 0; i < pois.length; i++) {
      const originalPOI = pois[i]
      const poi = transformedPOIs[i]
      const coords = extractCoordinates(originalPOI.geometry)
      
      // Prepare coordinate data
      const coordinateData = {
        latitude: coords.lat,
        longitude: coords.lon,
        elevation_m: null,
        boundary_type: 'point',
        boundary_source: 'osm',
        show_in_map: true,
        boundary_geometry: JSON.stringify({
          type: "Point",
          coordinates: [coords.lon, coords.lat]
        })
      }
      
        // Call RPC function
        console.log(`🔍 [SUPABASE] Calling RPC for POI ${i + 1}:`, {
          p_name: poi.name,
          p_city: poi.city,
          p_state: poi.state,
          p_osm_id: poi.osm_id,
          p_osm_type: poi.osm_type,
          p_lat: coords.lat,
          p_lon: coords.lon
        })
        
        const { data, error } = await supabase
          .schema('homolog')
          .rpc('create_poi_with_uuid', {
          p_name: poi.name || 'Unnamed POI',
          p_city: poi.city,
          p_state: poi.state,
          p_country: poi.country || 'Brazil',
          p_category: poi.category || 'unknown',
          p_osm_id: poi.osm_id,
          p_osm_type: poi.osm_type,
          p_place_id: poi.place_id,
          p_formatted_address: poi.formatted_address,
          p_importance: poi.importance,
          p_source_file: sourceFile,
          p_source_type: 'osm',
          p_is_complete: !!(poi.name && poi.city && poi.state),
          p_has_nominatim_data: poi.has_nominatim_data || false,
          p_processing_status: 'completed',
          p_osm_properties: poi.osm_properties || poi,
          p_approved: false,
          p_osm_geometry: originalPOI.geometry ? JSON.stringify(originalPOI.geometry) : null,
          p_description: poi.description || null,
          p_neighborhood: poi.neighborhood || null,
          p_street_name: poi.street_name || null,
          p_house_number: poi.house_number || null,
          p_postal_code: poi.postal_code || null,
          p_primary_category: poi.primary_category || poi.category || 'unknown',
          p_primary_category_type: poi.primary_category_type || null,
          p_categories: poi.categories || (poi.category ? [poi.category] : null),
          p_website: poi.website || null,
          p_contact_phone: poi.contact_phone || null,
          p_contact_email: poi.contact_email || null,
          p_operator_name: poi.operator_name || null,
          p_wheelchair_accessible: poi.wheelchair_accessible || null,
          p_wheelchair_toilets: poi.wheelchair_toilets || null,
          p_accessibility_notes: poi.accessibility_notes || null,
              p_height_m: poi.height_m || null,
              p_elevation_m: poi.elevation_m || null,
          p_building_material: poi.building_material || null,
          p_building_colour: poi.building_colour || null,
          p_roof_colour: poi.roof_colour || null,
          p_architectural_style: poi.architectural_style || null,
          p_historic_period: poi.historic_period || null,
          p_landmark_type: poi.landmark_type || null,
          p_architect: poi.architect || null,
          p_construction_status: poi.construction_status || null,
          p_start_date: poi.start_date || null,
          p_heritage_status: poi.heritage_status || null,
          p_unesco_status: poi.unesco_status || null,
          p_unesco_inscription_date: poi.unesco_inscription_date || null,
          p_unesco_reference: poi.unesco_reference || null,
          p_landmark_level: poi.landmark_level || null,
          p_importance_level: poi.importance_level || null,
          p_museum_type: poi.museum_type || null,
          p_museum_collection: poi.museum_collection || null,
          p_museum_audience: poi.museum_audience || null,
          p_museum_education: poi.museum_education || null,
          p_leisure_type: poi.leisure_type || null,
          p_natural_type: poi.natural_type || null,
          p_natural_water: poi.natural_water || null,
          p_sport_facilities: poi.sport_facilities || null,
          p_leisure_playground: poi.leisure_playground || null,
          p_monument_type: poi.monument_type || null,
          p_monument_event: poi.monument_event || null,
          p_monument_person: poi.monument_person || null,
          p_parking_capacity: poi.parking_capacity || null,
          p_public_transport: poi.public_transport || null,
          p_access_points: poi.access_points || null,
          p_entrance_fee: poi.entrance_fee || null,
          p_urban_density: poi.urban_density || null,
          p_noise_level: poi.noise_level || null,
          p_air_quality: poi.air_quality || null,
          p_shade_availability: poi.shade_availability || null,
          p_cultural_significance: poi.cultural_significance || null,
          p_local_traditions: poi.local_traditions || null,
          p_seasonal_attractions: poi.seasonal_attractions || null,
          p_is_historic: poi.is_historic || false,
          p_is_touristic: poi.is_touristic || false,
          p_has_train: poi.has_train || false,
          p_has_ferry: poi.has_ferry || false,
          p_has_bus: poi.has_bus || false,
          p_has_wheelchair_access: poi.has_wheelchair_access || false,
          p_has_water: poi.has_water || false,
          p_has_fishing: poi.has_fishing || false,
          p_has_playground: poi.has_playground || false,
          p_is_building: poi.is_building || false,
          p_has_ruins: poi.has_ruins || false,
          p_lat: coords.lat,
          p_lon: coords.lon,
          p_coordinate_data: coordinateData
        })

      if (error) {
        console.error(`❌ [SUPABASE] Error creating POI ${i + 1}:`, error)
        console.error(`❌ [SUPABASE] Error details:`, JSON.stringify(error, null, 2))
        return NextResponse.json({ 
          success: false, 
          error: `Failed to create POI: ${error.message}` 
        }, { status: 500 })
      }

      console.log(`🔍 [SUPABASE] RPC response for POI ${i + 1}:`, { data, error })
      
      if (data && data.length > 0) {
        const result = data[0]
        console.log(`🔍 [SUPABASE] Result details:`, { 
          poi_uuid_id: result.poi_uuid_id, 
          success: result.success, 
          message: result.message 
        })
        
        if (result.success) {
          results.push({ uuid_id: result.poi_uuid_id })
          console.log(`✅ [SUPABASE] POI ${i + 1} created: ${result.poi_uuid_id}`)
        } else {
          console.error(`❌ [SUPABASE] POI ${i + 1} creation failed:`, result.message)
        }
      } else {
        console.error(`❌ [SUPABASE] POI ${i + 1} creation failed: no data returned`)
      }
    }

    console.log(`✅ [SUPABASE] Successfully created ${results.length} POIs with coordinates`)

    return NextResponse.json({ 
      success: true, 
      imported: results.length,
      data: results.map(r => ({ uuid_id: r.uuid_id }))
    })

  } catch (error) {
    console.error('❌ [SUPABASE] Error in POIs API:', error)
    return NextResponse.json({ 
      success: false, 
      error: 'Internal server error' 
    }, { status: 500 })
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '50')
    const search = searchParams.get('search') || null
    const city = searchParams.get('city') || null
    const state = searchParams.get('state') || null
    const category = searchParams.get('category') || null
    const onlyComplete = searchParams.get('onlyComplete') === 'true' ? true : null

    const offset = (page - 1) * limit

    console.log(`📊 [SUPABASE] Fetching POIs: page=${page}, limit=${limit}`)

    // Use the custom function for pagination
    const { data, error } = await supabase
      .schema('homolog')
      .rpc('get_pois_paginated', {
        page_limit: limit,
        page_offset: offset,
        search_term: search,
        city_filter: city,
        state_filter: state,
        category_filter: category,
        only_complete: onlyComplete
      })

    if (error) {
      console.error('❌ [SUPABASE] Error fetching POIs:', error)
      return NextResponse.json({ 
        success: false, 
        error: error.message 
      }, { status: 500 })
    }

    const totalCount = data?.[0]?.total_count || 0
    const totalPages = Math.ceil(totalCount / limit)

    console.log(`✅ [SUPABASE] Fetched ${data?.length || 0} POIs (total: ${totalCount})`)

    return NextResponse.json({
      success: true,
      data: data || [],
      pagination: {
        page,
        limit,
        total: totalCount,
        totalPages,
        hasNext: page < totalPages,
        hasPrev: page > 1
      }
    })

  } catch (error) {
    console.error('❌ [SUPABASE] Error in POIs GET API:', error)
    return NextResponse.json({ 
      success: false, 
      error: 'Internal server error' 
    }, { status: 500 })
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const { ids } = await request.json()
    
    if (!ids || !Array.isArray(ids) || ids.length === 0) {
      return NextResponse.json({ error: 'No POI IDs provided' }, { status: 400 })
    }

    console.log(`🗑️ [SUPABASE] Deleting ${ids.length} POIs`)

    const { data, error } = await supabase
      .schema('homolog')
      .from('pois')
      .delete()
      .in('uuid_id', ids)
      .select('uuid_id')

    if (error) {
      console.error('❌ [SUPABASE] Error deleting POIs:', error)
      return NextResponse.json({ 
        success: false, 
        error: error.message 
      }, { status: 500 })
    }

    console.log(`✅ [SUPABASE] Successfully deleted ${data?.length || 0} POIs`)

    return NextResponse.json({
      success: true,
      deleted: data?.length || 0
    })

  } catch (error) {
    console.error('❌ [SUPABASE] Error in POIs DELETE API:', error)
    return NextResponse.json({ 
      success: false, 
      error: 'Internal server error' 
    }, { status: 500 })
  }
}
