-- ============================================================
-- BATCH 23 — Ireland: map province-level state → county
--            using city field as the lookup key
-- NOTE: Run AFTER batch25 (country = 'Ireland' not 'IE')
-- ============================================================
-- Background: all Irish POIs in DB have state = province
-- (Leinster/Munster/Connacht/Ulster). TopoJSON uses county-
-- level features. We remap state to county using city.
-- ============================================================

SELECT state, count(*) FROM core.attractions
 WHERE country = 'Ireland'
 GROUP BY state ORDER BY count DESC LIMIT 20;

-- Single-pass update: join against city→county mapping table
UPDATE core.attractions a
SET state = m.county
FROM (VALUES
  ('cork',                    'Cork'),
  ('skibbereen',              'Cork'),
  ('clonakilty',              'Cork'),
  ('bantry',                  'Cork'),
  ('macroom',                 'Cork'),
  ('dunmanway',               'Cork'),
  ('schull',                  'Cork'),
  ('castletownbere',          'Cork'),
  ('kinsale',                 'Cork'),
  ('cobh',                    'Cork'),
  ('mallow',                  'Cork'),
  ('youghal',                 'Cork'),
  ('ross carbery',            'Cork'),
  ('rosscarbery',             'Cork'),
  ('union hall',              'Cork'),
  ('kenmare',                 'Kerry'),
  ('dingle',                  'Kerry'),
  ('killarney',               'Kerry'),
  ('tralee',                  'Kerry'),
  ('listowel',                'Kerry'),
  ('cahirciveen',             'Kerry'),
  ('sneem',                   'Kerry'),
  ('waterville',              'Kerry'),
  ('galway',                  'Galway'),
  ('clifden',                 'Galway'),
  ('oughterard',              'Galway'),
  ('carraroe',                'Galway'),
  ('tuam',                    'Galway'),
  ('ballinasloe',             'Galway'),
  ('gort',                    'Galway'),
  ('kinvara',                 'Galway'),
  ('roundstone',              'Galway'),
  ('letterfrack',             'Galway'),
  ('leenane',                 'Galway'),
  ('westport',                'Mayo'),
  ('castlebar',               'Mayo'),
  ('ballina',                 'Mayo'),
  ('achill',                  'Mayo'),
  ('achill island',           'Mayo'),
  ('belmullet',               'Mayo'),
  ('louisburgh',              'Mayo'),
  ('newport',                 'Mayo'),
  ('knock',                   'Mayo'),
  ('dooagh',                  'Mayo'),
  ('keel',                    'Mayo'),
  ('keem',                    'Mayo'),
  ('foxford',                 'Mayo'),
  ('killala',                 'Mayo'),
  ('swinford',                'Mayo'),
  ('dublin',                  'Dublin'),
  ('rialto',                  'Dublin'),
  ('drumcondra',              'Dublin'),
  ('cabra',                   'Dublin'),
  ('fairview',                'Dublin'),
  ('raheny',                  'Dublin'),
  ('artane',                  'Dublin'),
  ('clontarf',                'Dublin'),
  ('glasnevin',               'Dublin'),
  ('ballymun',                'Dublin'),
  ('santry',                  'Dublin'),
  ('ringsend',                'Dublin'),
  ('irishtown',               'Dublin'),
  ('sandymount',              'Dublin'),
  ('portobello',              'Dublin'),
  ('swords',                  'Fingal'),
  ('malahide',                'Fingal'),
  ('balbriggan',              'Fingal'),
  ('donabate',                'Fingal'),
  ('rush',                    'Fingal'),
  ('lusk',                    'Fingal'),
  ('skerries',                'Fingal'),
  ('howth',                   'Fingal'),
  ('blanchardstown',          'Fingal'),
  ('mulhuddart',              'Fingal'),
  ('tallaght',                'South Dublin'),
  ('clondalkin',              'South Dublin'),
  ('lucan',                   'South Dublin'),
  ('rathcoole',               'South Dublin'),
  ('saggart',                 'South Dublin'),
  ('dun laoghaire',           'Dún Laoghaire–Rathdown'),
  ('blackrock',               'Dún Laoghaire–Rathdown'),
  ('stillorgan',              'Dún Laoghaire–Rathdown'),
  ('dundrum',                 'Dún Laoghaire–Rathdown'),
  ('dalkey',                  'Dún Laoghaire–Rathdown'),
  ('kilkenny',                'Kilkenny'),
  ('graiguenamanagh',         'Kilkenny'),
  ('thomastown',              'Kilkenny'),
  ('callan',                  'Kilkenny'),
  ('urlingford',              'Kilkenny'),
  ('freshford',               'Kilkenny'),
  ('kilmacow',                'Kilkenny'),
  ('goresbridge',             'Kilkenny'),
  ('bennettsbridge',          'Kilkenny'),
  ('castlecomer',             'Kilkenny'),
  ('waterford',               'Waterford'),
  ('dungarvan',               'Waterford'),
  ('tramore',                 'Waterford'),
  ('passage east',            'Waterford'),
  ('lismore',                 'Waterford'),
  ('wicklow',                 'Wicklow'),
  ('arklow',                  'Wicklow'),
  ('bray',                    'Wicklow'),
  ('greystones',              'Wicklow'),
  ('roundwood',               'Wicklow'),
  ('rathdrum',                'Wicklow'),
  ('glendalough',             'Wicklow'),
  ('wexford',                 'Wexford'),
  ('new ross',                'Wexford'),
  ('enniscorthy',             'Wexford'),
  ('gorey',                   'Wexford'),
  ('ennis',                   'Clare'),
  ('scarriff',                'Clare'),
  ('kilrush',                 'Clare'),
  ('lisdoonvarna',            'Clare'),
  ('lahinch',                 'Clare'),
  ('kilfenora',               'Clare'),
  ('doolin',                  'Clare'),
  ('ballyvaughan',            'Clare'),
  ('limerick',                'Limerick'),
  ('newcastle west',          'Limerick'),
  ('adare',                   'Limerick'),
  ('letterkenny',             'Donegal'),
  ('donegal',                 'Donegal'),
  ('bundoran',                'Donegal'),
  ('buncrana',                'Donegal'),
  ('killybegs',               'Donegal'),
  ('milford',                 'Donegal'),
  ('millford',                'Donegal'),
  ('ballyshannon',            'Donegal'),
  ('dungloe',                 'Donegal'),
  ('glenties',                'Donegal'),
  ('dunlewy',                 'Donegal'),
  ('ardara',                  'Donegal'),
  ('creeslough',              'Donegal'),
  ('carrigart',               'Donegal'),
  ('sligo',                   'Sligo'),
  ('strandhill',              'Sligo'),
  ('rosses point',            'Sligo'),
  ('manorhamilton',           'Leitrim'),
  ('carrick-on-shannon',      'Leitrim'),
  ('drumshanbo',              'Leitrim'),
  ('ballinamore',             'Leitrim'),
  ('dromahair',               'Leitrim'),
  ('mohill',                  'Leitrim'),
  ('roscommon',               'Roscommon'),
  ('boyle',                   'Roscommon'),
  ('athlone',                 'Westmeath'),
  ('mullingar',               'Westmeath'),
  ('moate',                   'Westmeath'),
  ('castlepollard',           'Westmeath'),
  ('tullamore',               'Offaly'),
  ('birr',                    'Offaly'),
  ('edenderry',               'Offaly'),
  ('banagher',                'Offaly'),
  ('clara',                   'Offaly'),
  ('portlaoise',              'Laoighis'),
  ('ballylinan',              'Laoighis'),
  ('abbeyleix',               'Laoighis'),
  ('longford',                'Longford'),
  ('navan',                   'Meath'),
  ('trim',                    'Meath'),
  ('kells',                   'Meath'),
  ('ashbourne',               'Meath'),
  ('drogheda',                'Louth'),
  ('dundalk',                 'Louth'),
  ('ardee',                   'Louth'),
  ('carlingford',             'Louth'),
  ('naas',                    'Kildare'),
  ('maynooth',                'Kildare'),
  ('celbridge',               'Kildare'),
  ('leixlip',                 'Kildare'),
  ('carlow',                  'Carlow'),
  ('muinebheag',              'Carlow'),
  ('bagenalstown',            'Carlow'),
  ('monaghan',                'Monaghan'),
  ('carrickmacross',          'Monaghan'),
  ('clones',                  'Monaghan'),
  ('cavan',                   'Cavan'),
  ('ballyconnell',            'Cavan'),
  ('ballyjamesduff',          'Cavan'),
  ('belturbet',               'Cavan'),
  ('ballinagh',               'Cavan'),
  ('cootehill',               'Cavan'),
  ('shercock',                'Cavan'),
  ('ballyhaise',              'Cavan'),
  ('coothill',                'Cavan'),
  ('kingscourt',              'Cavan'),
  ('bailieborough',           'Cavan'),
  ('clonmel',                 'South Tipperary'),
  ('cahir',                   'South Tipperary'),
  ('cashel',                  'South Tipperary'),
  ('cluain meala',            'South Tipperary'),
  ('nenagh',                  'North Tipperary'),
  ('roscrea',                 'North Tipperary'),
  ('thurles',                 'North Tipperary'),
  ('borrisoleigh',            'North Tipperary'),
  ('templemore',              'North Tipperary')
) AS m(city_slug, county)
WHERE a.country = 'Ireland'
  AND lower(trim(a.state)) IN ('leinster','munster','connacht','ulster','')
  AND lower(trim(a.city)) = m.city_slug;

-- Set remaining province-level states to NULL (unknown city → no region)
UPDATE core.attractions SET state = NULL
  WHERE country = 'Ireland'
    AND lower(trim(state)) IN ('leinster','munster','connacht','ulster');

-- Fix "Laois" → "Laoighis" (TopoJSON canonical spelling)
UPDATE core.attractions SET state = 'Laoighis'
  WHERE country = 'Ireland' AND lower(trim(state)) IN ('laois','laouis','laoigh');

-- Fix Tipperary: plain "Tipperary" → North Tipperary (most common)
UPDATE core.attractions SET state = 'North Tipperary'
  WHERE country = 'Ireland' AND lower(trim(state)) = 'tipperary';

-- Fix Dún Laoghaire–Rathdown spelling variants
UPDATE core.attractions SET state = 'Dún Laoghaire–Rathdown'
  WHERE country = 'Ireland'
    AND lower(trim(state)) IN ('dun laoghaire rathdown','dun laoghaire-rathdown',
                               'dún laoghaire-rathdown','dún laoghaire–rathdown');

SELECT state, count(*) FROM core.attractions
 WHERE country = 'Ireland'
 GROUP BY state ORDER BY count DESC LIMIT 30;
