-- ============================================================
-- BATCH 24 — UK: map nation-level state → council/authority
--            using city field as the lookup key
-- NOTE: Run AFTER batch25 (country = 'United Kingdom' not 'GB')
-- ============================================================
-- Background: all UK POIs in DB have state = nation
-- (England/Scotland/Wales/Northern Ireland). TopoJSON uses
-- council/unitary-authority-level features. We remap state
-- to council using city.
-- ============================================================

SELECT state, count(*) FROM core.attractions
 WHERE country = 'United Kingdom'
 GROUP BY state ORDER BY count DESC LIMIT 20;

-- Single-pass update: join against city→council mapping table
UPDATE core.attractions a
SET state = m.council
FROM (VALUES
  -- Northern Ireland
  ('enniskillen',         'Fermanagh'),
  ('lisnaskea',          'Fermanagh'),
  ('irvinestown',        'Fermanagh'),
  ('newtownbutler',      'Fermanagh'),
  ('rosslea',            'Fermanagh'),
  ('newry',              'Newry and Mourne'),
  ('crossmaglen',        'Newry and Mourne'),
  ('warrenpoint',        'Newry and Mourne'),
  ('armagh',             'Armagh'),
  ('portadown',          'Craigavon'),
  ('craigavon',          'Craigavon'),
  ('lurgan',             'Craigavon'),
  ('belfast',            'Belfast'),
  ('lisburn',            'Lisburn'),
  ('newtownabbey',       'Newtownabbey'),
  ('carnmoney',          'Newtownabbey'),
  ('antrim',             'Antrim'),
  ('ballymena',          'Ballymena'),
  ('ballymoney',         'Ballymoney'),
  ('bushmills',          'Moyle'),
  ('rathlin island',     'Moyle'),
  ('ballycastle',        'Moyle'),
  ('coleraine',          'Coleraine'),
  ('portrush',           'Coleraine'),
  ('portstewart',        'Coleraine'),
  ('limavady',           'Limavady'),
  ('derry',              'Derry'),
  ('londonderry',        'Derry'),
  ('strabane',           'Strabane'),
  ('omagh',              'Omagh'),
  ('dungannon',          'Dungannon'),
  ('coalisland',         'Dungannon'),
  ('moy',                'Dungannon'),
  ('cookstown',          'Dungannon'),
  ('magherafelt',        'Magherafelt'),
  ('castlewellan',       'Down'),
  ('downpatrick',        'Down'),
  ('banbridge',          'Banbridge'),
  ('rathfriland',        'Banbridge'),
  ('newtownards',        'Ards'),
  ('bangor',             'North Down'),
  ('holywood',           'North Down'),
  ('carrickfergus',      'Carrickfergus'),
  -- Scotland
  ('stornoway',          'Eilean Siar'),
  ('isle of lewis',      'Eilean Siar'),
  ('isle of harris',     'Eilean Siar'),
  ('benbecula',          'Eilean Siar'),
  ('isle of benbecula',  'Eilean Siar'),
  ('isle of north uist', 'Eilean Siar'),
  ('isle of south uist', 'Eilean Siar'),
  ('isle of barra',      'Eilean Siar'),
  ('inverness',          'Highland'),
  ('ullapool',           'Highland'),
  ('portree',            'Highland'),
  ('lairg',              'Highland'),
  ('mallaig',            'Highland'),
  ('fort william',       'Highland'),
  ('aviemore',           'Highland'),
  ('nairn',              'Highland'),
  ('wick',               'Highland'),
  ('thurso',             'Highland'),
  ('isle of skye',       'Highland'),
  ('skye',               'Highland'),
  ('kyle of lochalsh',   'Highland'),
  ('broadford',          'Highland'),
  ('isle of mull',       'Highland'),
  ('tobermory',          'Argyll and Bute'),
  ('ardrishaig',         'Argyll and Bute'),
  ('inveraray',          'Argyll and Bute'),
  ('oban',               'Argyll and Bute'),
  ('lochgilphead',       'Argyll and Bute'),
  ('isle of islay',      'Argyll and Bute'),
  ('islay',              'Argyll and Bute'),
  ('bowmore',            'Argyll and Bute'),
  ('kirkwall',           'Orkney'),
  ('stromness',          'Orkney'),
  ('pierowall',          'Orkney'),
  ('westray',            'Orkney'),
  ('rousay',             'Orkney'),
  ('lerwick',            'Shetland Islands'),
  ('symbister',          'Shetland Islands'),
  ('brae',               'Shetland Islands'),
  ('sandwick',           'Shetland Islands'),
  ('edinburgh',          'Edinburgh'),
  ('leith',              'Edinburgh'),
  ('glasgow',            'Glasgow'),
  ('govan',              'Glasgow'),
  ('partick',            'Glasgow'),
  ('aberdeen',           'Aberdeen'),
  ('dundee',             'Dundee'),
  ('broughty ferry',     'Dundee'),
  ('perth',              'Perthshire and Kinross'),
  ('pitlochry',          'Perthshire and Kinross'),
  ('st andrews',         'Fife'),
  ('kirkcaldy',          'Fife'),
  ('dunfermline',        'Fife'),
  ('glenrothes',         'Fife'),
  ('stirling',           'Stirling'),
  ('callander',          'Stirling'),
  ('falkirk',            'Falkirk'),
  -- Wales
  ('cardiff',            'Cardiff'),
  ('penarth',            'Cardiff'),
  ('swansea',            'Swansea'),
  ('mumbles',            'Swansea'),
  ('newport',            'Newport'),
  ('caerleon',           'Newport'),
  ('bangor',             'Gwynedd'),
  ('caernarfon',         'Gwynedd'),
  ('harlech',            'Gwynedd'),
  -- England
  ('london',             'Westminster'),
  ('westminster',        'Westminster'),
  ('manchester',         'Manchester'),
  ('birmingham',         'Birmingham'),
  ('leeds',              'Leeds'),
  ('sheffield',          'Sheffield'),
  ('bristol',            'Bristol'),
  ('liverpool',          'Liverpool'),
  ('cambridge',          'Cambridgeshire'),
  ('york',               'York'),
  ('oxford',             'Oxfordshire'),
  ('durham',             'Durham'),
  ('grassington',        'North Yorkshire'),
  ('hawes',              'North Yorkshire'),
  ('harrogate',          'North Yorkshire'),
  ('skipton',            'North Yorkshire'),
  ('scarborough',        'North Yorkshire'),
  ('whitby',             'North Yorkshire'),
  ('settle',             'North Yorkshire'),
  ('pateley bridge',     'North Yorkshire'),
  ('ingleton',           'North Yorkshire'),
  ('aysgarth',           'North Yorkshire'),
  ('reeth',              'North Yorkshire'),
  ('keswick',            'Cumbria'),
  ('windermere',         'Cumbria'),
  ('ambleside',          'Cumbria'),
  ('coniston',           'Cumbria'),
  ('grasmere',           'Cumbria'),
  ('carlisle',           'Cumbria'),
  ('penzance',           'Cornwall'),
  ('st ives',            'Cornwall'),
  ('newquay',            'Cornwall'),
  ('falmouth',           'Cornwall'),
  ('exeter',             'Devon'),
  ('torquay',            'Devon'),
  ('dartmouth',          'Devon'),
  ('totnes',             'Devon'),
  ('southampton',        'Hampshire'),
  ('winchester',         'Hampshire'),
  ('michelmersh',        'Hampshire'),
  ('brighton',           'Brighton and Hove'),
  ('hove',               'Brighton and Hove'),
  ('tipton',             'Sandwell'),
  ('rowley regis',       'Sandwell'),
  ('smethwick',          'Sandwell'),
  ('telford',            'Telford and Wrekin'),
  ('shrewsbury',         'Shropshire'),
  ('gloucester',         'Gloucestershire'),
  ('cheltenham',         'Gloucestershire'),
  ('norwich',            'Norfolk'),
  ('ipswich',            'Suffolk'),
  ('newcastle',          'Newcastle upon Tyne'),
  ('hull',               'Kingston upon Hull'),
  ('yorkshire',          'North Yorkshire'),
  ('west yorkshire',     'Leeds')
) AS m(city_slug, council)
WHERE a.country = 'United Kingdom'
  AND lower(trim(a.state)) IN ('england','scotland','wales','northern ireland',
                               'great britain','gb','uk','')
  AND lower(trim(a.city)) = m.city_slug;

-- Set remaining nation-level states to NULL (unknown city → no region)
UPDATE core.attractions SET state = NULL
  WHERE country = 'United Kingdom'
    AND lower(trim(state)) IN ('england','scotland','wales','northern ireland',
                               'great britain','gb','uk');

SELECT state, count(*) FROM core.attractions
 WHERE country = 'United Kingdom'
 GROUP BY state ORDER BY count DESC LIMIT 40;
