-- Migration: Add generated_by tracking to attraction_descriptions
-- Purpose: Track which user (app user, CMS admin, or system) generated each description
-- This enables analytics to distinguish system-generated vs user-generated descriptions

-- Add generated_by_user_id: the Supabase Auth UUID of who triggered the generation
ALTER TABLE core.attraction_descriptions
ADD COLUMN IF NOT EXISTS generated_by_user_id uuid NULL;

-- Add generated_by_email: human-readable identifier for quick analysis
ALTER TABLE core.attraction_descriptions
ADD COLUMN IF NOT EXISTS generated_by_email text NULL;

-- Add generated_by_source: categorized source for easy filtering
-- Values: 'app_user' (users on the street), 'cms_admin' (CMS operators), 'system' (automated batch)
ALTER TABLE core.attraction_descriptions
ADD COLUMN IF NOT EXISTS generated_by_source text NULL DEFAULT 'system';

-- Index for analytics queries: "show me all descriptions generated by app users"
CREATE INDEX IF NOT EXISTS idx_descriptions_generated_by_source
ON core.attraction_descriptions (generated_by_source);

-- Index for user-specific queries: "show me all descriptions generated by user X"
CREATE INDEX IF NOT EXISTS idx_descriptions_generated_by_user
ON core.attraction_descriptions (generated_by_user_id)
WHERE generated_by_user_id IS NOT NULL;

COMMENT ON COLUMN core.attraction_descriptions.generated_by_user_id IS 'Supabase Auth UUID of the user who triggered this description generation';
COMMENT ON COLUMN core.attraction_descriptions.generated_by_email IS 'Email of the user who triggered this description generation';
COMMENT ON COLUMN core.attraction_descriptions.generated_by_source IS 'Source category: app_user, cms_admin, or system';
